### ISSUE TITLE
FormatException: Unrecognized Guid format. - when importing solution into vanilla environment

### ISSUE THREAD

**Issue by ameed** [microsoft/powerplatform-build-tools#1041]
### Discussed in https://github.com/microsoft/powerplatform-build-tools/discussions/1040

<div type='discussions-op-text'>

<sup>Originally posted by **ameed** September 17, 2024</sup>
We tried to make first import of solution to a new environment using release pipeline and Az DevOps PP Build Tools and got this error even before solution import started. This hinted us that something was wrong with the solution zip file. However when tried to import the solution to an existing environment (where the solution was already earlier imported), this error did not occur.

On debugging, we found that recently something changed in solution export process, for environment variables. If an env variable is defined with a default value is set in Source Environment, the environmentvariablevalues.json file does not have the environmentvariablevalueid attribute, so the JSON looks like following. 
{
  "environmentvariablevalues": {
    "environmentvariablevalue": {
      "iscustomizable": "1"
    }
  }
}

In our source control we found this change first show up on Sept 9 as we exported using PP Build Tools, so previously the same JSON looked like this:
{
  "environmentvariablevalues": {
    "environmentvariablevalue": {
      "@environmentvariablevalueid": "953f8826-85a9-ed11-aacf-000d3a0c29b6",
      "iscustomizable": "1"
    }
  }
}

When i looked into PAC log file, i found the following stack trace, which clearly mentions that exception is arising from trying to parse a blank string as Guid. Using ILSpy, i located "GenerateSchemaNameToValueIdMapping" method in "bolt.dataverse.dll". I shall also report this issue to Microsoft, but i believe if guid of an environmentvariable value is not provide in solution zip package then import process should not try to create a value during import process 

2024-09-17 01:49:58.2572 | ERR | bolt.dataverse.client.actions.SolutionImportAction :: Caught Exception in ActionBase of: Unrecognized Guid format.|EXCEPTION: System.FormatException: Unrecognized Guid format.
   at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)
   at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result)
   at System.Guid..ctor(String g)
   at bolt.dataverse.client.actions.SolutionImportAction.GenerateSchemaNameToValueIdMapping(List`1 componentDetails)
   at bolt.dataverse.client.actions.SolutionImportAction.Execute(String solutionZipPath, ImportSolutionSettings importSettings)

</div>

**Comment by 568182** [comment]
**We also facing exactly the same issue, When we deploy solution into new production environment.**

**Note:** When we deploy the same solution in test environment (sandbox) below error did not occur. 

[ ' info: bolt.dataverse.client.actions.SolutionImportAction[0]' ]
[ ' Executing SolutionImportAction' ]
[ ' Solution Importing...' ]
[ ' fail: bolt.dataverse.client.actions.SolutionImportAction[0]' ]
[  ' Caught Exception in ActionBase of: Unrecognized Guid format.' ]
[ ' System.FormatException: Unrecognized Guid format.' ]
[ ' at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)']
[  ' at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result)' ]
[ ' at System.Guid..ctor(String g)' ]
[ 'at bolt.dataverse.client.actions.SolutionImportAction.GenerateSchemaNameToValueIdMapping(List`1 componentDetails)' ]
[ ' at bolt.dataverse.client.actions.SolutionImportAction.Execute(String solutionZipPath, ImportSolutionSettings importSettings)']
[ 'Microsoft PowerPlatform CLI' ]
[ 'Version: 1.34.4+gbc3320d' ]
[ 'Online documentation: https://aka.ms/PowerPlatformCLI' ]
[ ' Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions' ]
[ 'Error: Unrecognized Guid format.' ]
[ 'info: bolt.cli.CommandProcessor[0]' ]
[ '      EndExecutingVerb (Success: False, Execution Time(ms): 117)' ]
[ 'info: bolt.Session[0]' ]
[ ' End session. (sessionId: b89cd516-d996-4f8e-9724-8c712171eaa1; ResponseCode: 500)']
[ '      ' ]
##[error]error: 1
##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;]error: 1
##[error]failed: info: bolt.Session[0]
      Product Version: 1.34.4+gbc3320d; File Version: 1.34.4
info: bolt.Session[0]

**Comment by ameed** [comment]
We worked around this issue as follows:

Using pac cli or pp build tools:
Before export from source environment, remove the default value from environment variables. Publish and export. Add target environment specific environment variables values in deployment settings json file and import

**Comment by 568182** [comment]
Thanks for your response Ameed Sheikh.

**Comment by 568182** [comment]
Hi Ameed, I tried the above approach, unfortunately it didn't work for me. 

I tried disabling **Export value** in the **Advanced** section, which did work for me in this case.

![image](https://github.com/user-attachments/assets/18277885-fd3d-4e46-885d-d17319d869b1)

Thanks for your quick response and guiding me further.

**Comment by manishmoothedath** [comment]
Tried all the above suggestions still I get the error. I don't have any environment variables with a Guid.

"Error: Unrecognized Guid format."

**Comment by tocri** [comment]
> Hi Ameed, I tried the above approach, unfortunately it didn't work for me.
> 
> I tried disabling **Export value** in the **Advanced** section, which did work for me in this case.
> 
> ![image](https://private-user-images.githubusercontent.com/171143616/369090887-18277885-fd3d-4e46-885d-d17319d869b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NTkzODgsIm5iZiI6MTcyNzQ1OTA4OCwicGF0aCI6Ii8xNzExNDM2MTYvMzY5MDkwODg3LTE4Mjc3ODg1LWZkM2QtNGU0Ni04ODVkLWQxNzMxOWQ4NjliMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyN1QxNzQ0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2ZhNzQxMDViMDcxOGQ1NzQ3OWRhMWY3N2NjNDZiODBiNmUxYTViZjc4MDA1YTNhYWIyYzBjNDYwYzEwNDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pcQuHa31aahy3I1lsE5F9SlW8h1deqYzUPF6Td3iRN4)
> 
> Thanks for your quick response and guiding me further.

Works for me with ALM Accelerator. Thank you so much

**Comment by petrochuk** [comment]
we released PAC CLI 1.35 which ignores invalid GUIDs

**Comment by ameed** [comment]
Thank you 👍

**Comment by greggdavenport** [comment]
> we released PAC CLI 1.35 which ignores invalid GUIDs

Thank you, and when might this version back the GitHub action for importing solutions?
