### ISSUE TITLE
DeployPackage fails to load package dll - "Could not load assembly CrmPackageExtentionBase"

### ISSUE THREAD

**Issue by amitvirendra** [microsoft/powerplatform-build-tools#125]
The changes are not backward compatible. Our pipelines started failing as soon as you are making chnages. It failed on June 14 as well. that worked after the changes were reverted. It will be good, if you allow the clients to control the version so that they can work out by keeping old version while you guys try to test out the new changes. As of now, it breaks our PROD systems.

error: 1
failed: Reading the import configuration. Please wait.
Failed to Load the Import Configuration : Config File Missing
Failed to Load the Import Configuration : Config File Missing
Microsoft PowerPlatform CLI
Version: 1.15.9+gf60807f
Error: Failed to Load the Import Configuration : Config File Missing
Usage: pac package deploy [--logFile] [--logConsole] --package
  --logFile                   Log file path (alias: -lf)
  --logConsole                Output log to console (alias: -c)
  --package                   path to a package dll or zip file with a package (alias: -p)
1 more errors. Click on expand view in the context menu to view complete logs.

**Comment by davidjenni** [comment]
@amitvirendra what are the more detailed errors, both in the log, but also in the DeployPackage detail log that is saved to the AzDevOps run's artifact store?

RE: versioning: It was a conscious choice by the team, as it has the least amount of pain on existing customers. Since both the old PS based and the pac CLI based versions do depend on having an initial ToolInstaller, there is no mix and match between e.g. @0 ToolInstaller and a @1 DeployPackage task.

**Comment by Faranakt** [comment]
We are having the exact same issue ! this is stoping us to do deployment , we need this fixed urgently

**Comment by davidjenni** [comment]
@amitvirendra @Faranakt we understand the urgency. Here's what I've gleaned so far from the above logs:
- any error in the PackageDeployer code itself (this is C# code shared between the former PS PP-BT and the C# pac CLI now) is expected to be written to the detailed deployer log, e.g. indicated in the log above as:
`--logFile C:\_a\out\DeployPackage\deploy-package\DeploymentPackage-2022-06-30T19-34-33.281Z.log`
This log will assist package/pipeline owners to further debug.
- to add insult to injury, even though the new PP-BT now by default ensures that this detail log is always a) captured and b) uploaded into AzDevOps run logs (as artifact for build pipelines, or as separate log to the overall log store for release pipelines), that code path ended up erroring out, see the nodejs runtime errors.
- the one odd thing in the log is the double mentioning of "Failed to Load the Import Configuration : Config File Missing":
while not useful to the user, it helped me correlate with the PD core src code that this happens only when the package dll could not be loaded via reflection (std procedure for PD). This hints that the newer version of the PD core lib that ships with this PP-BT wasn't able to load the DLL, typ, that is an issue with missing dependent assemblies

We have 2 tracking bugs on our end:
- highest prio: fix the missing logs issue, so users can diagnose e.g. why the pkg dll could not be loaded
AB#2776373
-   fix PD to not double print the same error, but actually indicate more why the dll failed to load
AB#2776344

The first fix should be ready later today PDT

**Comment by davidjenni** [comment]
@amitvirendra @Faranakt the fix to at be able to capture and upload the PD core library's detail log is now deployed as 1.0,82.
This log file should help to further investigate WHY the package dll failed to load. Either quote parts here, or forward to my MSFT corp email address with my alias, davidjen

- In build pipelines, the log is added into a separate "DeployPackage" artifact, available from the job's summary, see: artifacts
- In release pipelines, the log is part of the "Download all logs" zip file, named as: `<packageName>-<timestamp>.log`
![image](https://user-images.githubusercontent.com/3200210/176809016-ad2e0905-6157-415e-aad0-dd82127752ff.png)

**Comment by pj68811** [comment]
> It will be good, if you allow the clients to control the version so that they can work out by keeping old version while you guys try to test out the new changes. As of now, it breaks our PROD systems.

I agree, devops even allow for versioning of tasks. Sadly, this has not been used. 
![image](https://user-images.githubusercontent.com/97521375/176994459-4495d0e7-ff97-4d27-bf5b-cf2c3ca861ea.png)

**Comment by amitvirendra** [comment]
here are all logs. I masked the sensitive info
[ReleasePipeline_Logs_07052022.zip](https://github.com/microsoft/powerplatform-build-tools/files/9049848/ReleasePipeline_Logs_07052022.zip)
.

**Comment by davidjenni** [comment]
@amitvirendra thank you for the log file, this confirms the issue.
We have an internal tracking bug:
AB#2776373: PP.BT: PackageDeploy: PD-Core fails to load the pkg dll - Could not load file or assembly 'Microsoft.Xrm.Tooling.PackageDeployment.CrmPackageExtentionBase, Version=1.0.0.0

I'll leave this issue open until we have a fix ready. I will resolve duplicate issues to this one.

**Comment by davidjenni** [comment]
Part of PP-BT v2.0.3 and newer
https://aka.ms/pp-bt-migrate-to-v2
