### ISSUE TITLE
Tasks fail to authenticate with exceptionId when targeting crm19/NOR DV environments

### ISSUE THREAD

**Issue by larhem** [microsoft/powerplatform-build-tools#128]
We had a working pipline until updating to 1.0.82.

Now some or our pipelines are failing on the step using "Power Platform Publish Customiztions".

![image](https://user-images.githubusercontent.com/91886096/176837064-490bdb45-4ca5-422d-89e7-ede1244785a9.png)

Some of the error output:

##[debug]authenticationType=PowerPlatformSPN
##[debug]PowerPlatformSPN=84948b0a-4261-47db-bf30-2fd5e8a1e0af
##[debug]84948b0a-4261-47db-bf30-2fd5e8a1e0af exists true
##[debug]84948b0a-4261-47db-bf30-2fd5e8a1e0af=https://**************************/
##[debug]Environment=$(BuildTools.EnvironmentUrl)
Discovered environment url from explicit input parameter 'Environment': $(BuildTools.EnvironmentUrl)
##[debug]Discovered environment url from explicit input parameter 'Environment': $(BuildTools.EnvironmentUrl)
##[debug]IsolateVarRef: $(BuildTools.EnvironmentUrl) -> BuildTools.EnvironmentUrl (isRefExpression=true)
Discovered Azure DevOps variable expression that needs resolving: $(BuildTools.EnvironmentUrl) -> BuildTools.EnvironmentUrl
##[debug]Discovered Azure DevOps variable expression that needs resolving: $(BuildTools.EnvironmentUrl) -> BuildTools.EnvironmentUrl
##[debug]BuildTools.EnvironmentUrl=undefined
##[debug]PowerPlatformCreateEnvironment_BuildTools_EnvironmentUrl=undefined
##[debug]PowerPlatformCopyEnvironment_BuildTools_EnvironmentUrl=undefined
##[debug]PowerPlatformResetEnvironment_BuildTools_EnvironmentUrl=undefined
##[debug]PowerPlatformRestoreEnvironment_BuildTools_EnvironmentUrl=undefined
##[debug]authenticationType=PowerPlatformSPN
##[debug]PowerPlatformSPN=84948b0a-4261-47db-bf30-2fd5e8a1e0af
##[debug]84948b0a-4261-47db-bf30-2fd5e8a1e0af=https://**************************/
Falling back to url from service connection, using: https://**************************/
##[debug]Falling back to url from service connection, using: https://**************************/
##[debug]POWERPLATFORMTOOLS_PACCLIPATH=D:\a\_tasks\PowerPlatformToolInstaller_8015465b-f367-4ec4-8215-8edf682574d3\0.0.82\bin
##[debug]command: D:\a\_tasks\PowerPlatformToolInstaller_8015465b-f367-4ec4-8215-8edf682574d3\0.0.82\bin\pac\tools\pac.exe, first arg of 12: auth
[ 'Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: 63f8ebd7-4fcb-4d16-993f-d5113c1499d0, Exception Type: System.NotImplementedException' ]
[ 'The diagnostic logs can be found at: D:\\a\\_tasks\\PowerPlatformToolInstaller_8015465b-f367-4ec4-8215-8edf682574d3\\0.0.82\\bin\\pac\\tools\\logs\\pac-log.txt' ]
##[error]error: 1
##[debug]Processed: ##vso[task.issue type=error;]error: 1
##[error]failed: Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: 63f8ebd7-4fcb-4d16-993f-d5113c1499d0, Exception Type: System.NotImplementedException

**Comment by larhem** [comment]
We have created a suport ticket at Microsoft. It looks like there is a problem on connection to some of our environments since we are getting errors using CLI outside of pipelines as well.

**Comment by davidjenni** [comment]
@larhem issue is understood:
this happens on the pac auth create part of the task (it never gets to the actual PublishCustomizations part):
From the incident ticket, I see that the envURL is one in crm19 (NOR). The version used in the PP-BT does not have that support yet, we're working on a fix

Changing issue title from:
Issues with "Publish customizations" after latest release

**Comment by davidjenni** [comment]
fixes are underway, tracking item: AB#2777670

**Comment by davidjenni** [comment]
fix is queued up, but we'll wait until after the holiday weekend (7/4 is Independence Day) to continue

**Comment by davidjenni** [comment]
@larhem we had to roll back to the PS implementation (see #144), so the actual fix for NOR support will wait until we're ready to switch back to the new pac CLI based PP-BT (late July).
The PS based PP-BT 1.0.41 (now: 1.0.85) did not have explicit region support, but mostly worked, likely even in your pipelines?
I will leave this issue open until we deploy the next PP-BT

**Comment by davidjenni** [comment]
@larhem  today we'll begin rolling out the PP-BT v2 (keeping the PS-based v0 in place side-by-side). Once available on your AzDO org, please migrate to v2 which is pac CLI based:
https://aka.ms/pp-bt-migrate-to-v2
