### ISSUE TITLE
Power Platform Solution Import Task v0.0.82 failing to import in the final PublishCustomizations part, even if tasks is running async

### ISSUE THREAD

**Issue by MannyGrewal** [microsoft/powerplatform-build-tools#129]
Hi there,
Eversince the upgrade last week from 0.0.77 to 0.0.82 our solution is not getting imported and consistently failing with this new Asynchronous import model.

We are getting this error
 'Error: The request channel timed out while waiting for a reply after 00:04:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.' ]

The settings for your import task are
 -AsyncOperation: true
 -MaxAsyncWaitTime: '240' # 4 hours

Below are the full logs
Starting: Import xxxxxxxxxxx
==============================================================================
Task         : Power Platform Import Solution
Description  : Power Platform Import Solution
Version      : 0.0.82
Author       : Microsoft
Help         : [More Info](https://aka.ms/buildtoolsdoc)
==============================================================================
Discovered environment url from explicit input parameter 'Environment': $(BuildTools.EnvironmentUrl)
Discovered Azure DevOps variable expression that needs resolving: $(BuildTools.EnvironmentUrl) -> BuildTools.EnvironmentUrl
Falling back to url from service connection, using: https://xxxxxxxxxxxxxxx/ /
[ 'Authentication successfully created.' ]
[ 'Validating connection...' ]
[ 'Connected to...xxxxxxxxxxxxxx' ]
[ '    * DATAVERSE                                https://xxxxxxxxxxxxxxx/ : ***     xxxxx' ]
[ '' ]
[ 'The Authentication Result: Authentication successfully created.,Validating connection...,Connected to...xxxxxxx,    * DATAVERSE                                https://xxxxxxxxxxxxxxxxx/ : ***     xxx,' ]
[ 'Calling pac cli inputs: solution import --path D:\\a\\1\\Self\\Solutions\\Unmanaged\\Zip\\xxxx.zip --async true --import-as-holding False --force-overwrite True --publish-changes true --skip-dependency-check True --convert-to-managed false --max-async-wait-time 240 --activate-plugins false' ]
[ 'Connected to...xxxxxxxxxxxxxx' ]
[ 'Solution Importing...' ]
[ 'Waiting for asynchronous operation 29ff8a16-22f9-ec11-82e7-00224815993b to complete with timeout of 04:00:00' ]
[ 'Processing asynchronous operation... execution time: 00:00:00 and 1% complete' ]
[ 'Processing asynchronous operation... execution time: 00:00:04 and 2% complete' ]
Processing asynchronous operation... execution time: 00:44:41 and 100% complete
Processing asynchronous operation... execution time: 00:44:45 and 100% complete
Processing asynchronous operation... execution time: 00:44:50 and 100% complete
Processing asynchronous operation... execution time: 00:44:54 and 100% complete
Processing asynchronous operation... execution time: 00:44:58 and 100% complete
Asynchronous operation 29ff8a16-22f9-ec11-82e7-00224815993b successfully finished within 00:45:02.3630415
Publishing All Customizations...
Microsoft PowerPlatform CLI
Version: 1.15.9+gf60807f

Error: The request channel timed out while waiting for a reply after 00:04:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
    The HTTP request to '[https://xxxxxxxxxxxxx/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.47.7698'](https://xxxxxxxxxxxxx/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.47.7698%27) has exceeded the allotted timeout of 00:04:00. The time allotted to this operation may have been a portion of a longer timeout.
        The operation has timed out

Usage: pac solution import [--path] [--activate-plugins] [--force-overwrite] [--skip-dependency-check] [--import-as-holding] [--publish-changes] [--convert-to-managed] [--async] [--max-async-wait-time] [--settings-file]

  --path                      Path to solution zip file. If not specified, assumes the current folder is a cdsproj project. (alias: -p)
  --activate-plugins          Activate plug-ins and workflows on the solution (alias: -ap)
  --force-overwrite           Force an overwrite of unmanaged customizations (alias: -f)
  --skip-dependency-check     Skip dependency check against dependencies flagged as product update (alias: -s)
  --import-as-holding         Import the solution as a holding solution (alias: -h)
  --publish-changes           Publish your changes upon a successful import (alias: -pc)
  --convert-to-managed        Convert as Managed Solution (alias: -cm)
  --async                     Imports solution asynchronously (alias: -a)
  --max-async-wait-time       Max asynchronous wait time in minutes. Default value is 60 minutes (alias: -wt)
  --settings-file             The .json file with the deployment settings for connection references and environment variables.

The same code ran like breeze on the previous version last week.

**Comment by mgowing** [comment]
I am experiencing this issue too.

**Comment by paulbreuler** [comment]
Thank you for your patience, we have identified the problematic code and are working on a solution now. The fix will ensure that when the solution import task has both "Import solution as asynchronous operation" and "Publish All Customizations" set to true **the publish step will be asynchronous.**

**Proposed solution**
- Introduce task input parameter for publish all in Power Platform Build Tools
- Correct underlying code to treat async requests in similar fashion between import and publish based on task input

**Comment by davidjenni** [comment]
Our fixes to pac CLI and the import solution tasks have been merged. We're now kicking off our official build for an updated v >= 1.0.83 that has the fixes. ETA ~3:30 PDT today

Rel notes:
- 'Import Solution' task:
  - 'ActivatePlugins' task parameter is on by default; deprecate param 'PublishWorkflows' but consider both for plugin activation (#131)
  - fix forced 'PublishChanges' and its potential http timeout on PublishAllCustomizations (#129)
  - introduces a new "PublishCustomizationChanges" task parameter to also publish customizations after successful import

**Comment by davidjenni** [comment]
Fix has been deployed to VS Marketplace as 1.0,84

**Comment by MannyGrewal** [comment]
We are verifying the fix and will let you know later today. Thanks for the quick action to resolve this.

**Comment by MannyGrewal** [comment]
We have run some import tasks using the .84 build and it seems the issue reported above is resolved. However, there are two observations.

1. If we use the sync mode with import solution task (0.84) and the task times out after 4 minutes due to a bigger solution size, the job that this task started (which eventually timed out) stays hung as Started... for around 45 minutes blocking any further imports on the instance. Earlier such jobs healed quickly within 5 minutes.
2. The publish operation done via PowerPlatformPublishCustomizations task is timing out after 4 minutes.
Not sure if its related the bug fixes done yesterday but thought of letting you know our observations.

Thanks
Manny

**Comment by davidjenni** [comment]
I will leave this issue active and resolve any duplicates to it.

Our internal bug where we track the pac CLI and other work is this one:
AB#2780591: PP.BT / pac CLI deploy package: deployment errors out once accessToken has expired

**Comment by davidjenni** [comment]
@MannyGrewal 's original observation and the original title captured the core issue:
- ImportSolution does the actual staging and import of the solution,zip
- it has an option to, once the actual solution is imported, to also have it published
- it was that latter PublishCustomization that failed to conclude since that Dataverse API call originally only existed as a Synchronous call, i.e. it is subject to the std http-idle-connection timeout that http proxies and the Dataverse datacenter edges/TrafficManager enforce -> it results in the originally reported error:

```
[ 'Solution Importing...' ]
[ 'Waiting for asynchronous operation 29ff8a16-22f9-ec11-82e7-00224815993b to complete with timeout of 04:00:00' ]
[ 'Processing asynchronous operation... execution time: 00:00:00 and 1% complete' ]
<snip/>
Processing asynchronous operation... execution time: 00:44:58 and 100% complete
Asynchronous operation 29ff8a16-22f9-ec11-82e7-00224815993b successfully finished within 00:45:02.3630415
Publishing All Customizations...
Microsoft PowerPlatform CLI
Version: 1.15.9+gf60807f

Error: The request channel timed out while waiting for a reply after 00:04:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
```

The pac CLI that is in the PP-BT v2.0.3 and newer does correctly call the async PublishCustomization if the import solution task has the Asynch task option set.

Resolving this issue

Note: I mistakenly duped this issue with #139, but those are actually NOT dupes. The other issue is about renewal of an accessToken after 60 min.
