### ISSUE TITLE
Virtual Machine scale set self hosted agent PackageManagement dependency

### ISSUE THREAD

**Issue by eleung83** [microsoft/powerplatform-build-tools#147]
Using Virtual Machine scale sets for running our build pipelines in Azure means that the latest version of any powershell packages are also automatically installed.

5 days ago it looks like the PackageManagement package was updated to v1.4.8.1 [PackageManagement](https://www.powershellgallery.com/packages/PackageManagement/1.4.8.1)

This means that all agents spun up on demand will have this new version of the powershell package installed.

This causes a problem with the Power Platform Tool Installer as it seems like it is explicitly expecting v1.4.7 to be installed instead.

As a workaround it's possible to run a separate power shelll script that will install PackageManagement v1.4.7 alongside so that the Tool Installer package can run, but long term this isn't really a proper fix

![image](https://user-images.githubusercontent.com/26326026/177520341-8328e255-3b82-4862-b87a-0e188555e7ae.png)

**Comment by davidjenni** [comment]
@eleung83 PackageManagement is the standard PS manager, and for years (ever since we created the PP-BT PS version) 1.4.7 was the latest version on PSGallery, and it was the one utilized in ToolInstaller (since the Desktop PS default of 1.0.0.1 doesn't support nuget package install).

This error of not finding 1.4.7 (even though it is still published in PS Gallery) seems to be a very specific issue that so far only reproes on MSFT internal OneBranch agent VM images. We tried to repro on multiple public hosted agents, e.g. "Azure Pipelines" with windows-latest, windows-2022 etc, but all works as expected.

We are working on a hotfix for the PP-BT PS-based task in PROD to remediate this for our 1st party customers within MSFT

ETA later today Thu 7/7

**Comment by eleung83** [comment]
I thought I'd run some more tests based on what you mentioned above to see the difference between the Azure pipelines VM and our self hosted VMs using an OS from the Azure marketplace. I switched between using the windows-2022 image (Azure pipelines hosted agent) and a self hosted virtual machine using Windows Server 2022 datacenter (SKU 2022-datacenter-core-g2).

Using the Wndows-2022 agent specification, I ran a powershell script as the first task of the build pipeline to see what version of PackageManagement was installed, and it looks like it comes "pre-installed" with v1.4.7 (not surprising as this is a custom flavour of a Windows 2022 datacenter image used for azure pipelines with extra software preloaded and isn't available in Azure for public replication).

Running the same powershell script using one of the Windows 2022 Datacenter images available on the marketplace in Azure, the output from the powershell script showed that this module isn't yet installed (again makes sense as I'm guessing the images on the azure marketplace are just the vanilla OS with nothing else installed).

Hence, I'm guessing the PP BT Tool Installer task looks to install the latest version of the PackageManagement module from the web (if it's not currently installed on the VM running the pipeline task), but is expecting that v1.4.7 is being installed (not surprising as it has been a couple of years since this module was updated before 6 days ago)? 

I'm also guessing at some point this same module will get updated to the latest version available on the images used by the Microsoft hosted agents images, but manually whenever they decide to update the modules within these custom images.

**Comment by davidjenni** [comment]
@eleung83 the latest 1.0.89 of PP-BT does include an update to the latest PS PackageManagment, fixing the initial issue.

Today, we'll also publish a new v2 of the PP-BT (side-by-side, leaving the current v0 PS-based implementation intact) that is using .NET instead.
See also https://aka.ms/pp-bt-migrate-to-v2
