### ISSUE TITLE
create set-connection-variables task to return data from service connection

### ISSUE THREAD

**Issue by devkeydet** [microsoft/powerplatform-build-tools#148]
The repo below has a task that creates a [Dataverse connection string](https://docs.microsoft.com/en-us/powerapps/developer/data-platform/xrm-tooling/use-connection-strings-xrm-tooling-connect) to the Environment based on the provided Service Connection and stores it in a pipeline secret variable. Having such a inbuilt capability inside the Power Platform Built Tools would prevent the need to maintain the same credentials twice to support script tasks that need to connect to the same Dataverse environment using tools such as Xrm.Data.PowerShell and others that support the connection string format.  

https://github.com/remyblok/PowerPlatformBuildToolsEx

WhoAmI already validates the connection and sets additional variables such as BuildTools.EnvironmentID.  I am proposing extending WhoAmI task to support returning additional values.

**Comment by devkeydet** [comment]
Changed the issue name.  Upon further thought, it feels like adding this to WhoAmI is overloading the purpose of the WhoAmI task.  Proposing a new task instead.

**Comment by paulbreuler** [comment]
Great suggestion @devkeydet! let's explore this idea further.
