### ISSUE TITLE
Power platform solution checker fails with "Exceeded the max wait"

### ISSUE THREAD

**Issue by pj68811** [microsoft/powerplatform-build-tools#149]
Since v0.0.77 (and still in 0.0.85) we often (not always) are getting the following error in the output logs

**##[error]Exceeded the max wait. Try running again with an increased SecondsBetweenChecks and MaxStatusChecks.**

There is no option for the task to extend the wait time, except the default timeout built into any devops task (which has no affect). The timeout seems to be locked at 5min, which is probably fine since when the check works on the same solution it takes about 30seconds. The logs saved in the output folder do not indicate any other error. 

I've attached the an image showing output of unsuccessful check and successful next to each other. Both checking the same solution

![image](https://user-images.githubusercontent.com/97521375/177812963-83a357a8-d717-49e2-a1e9-3803d591bf47.png)

**Comment by pj68811** [comment]
I'm not sure extending the timeout is going to resolve all the issues though. The example I show above, in this case if it works it takes 30seconds, and if it doesn't it's just hanging there. As of today the timeout has been extended for the task, but we just hit the built in timeout of any task in devops.

**Comment by davidjenni** [comment]
The initial issue here was with the Checker task, which indeed had an issue with a fixed 5min task timeout.

If you see timeout issues in other tasks, please do open separate issues
