### ISSUE TITLE
Enhancement: Sorting in unpacked solutions

### ISSUE THREAD

**Issue by SiPurdy** [microsoft/powerplatform-build-tools#152]
When solutions are unpacked, it would be helpful if certain XML fragments were sorted as dynamics returns them in random orders each export. Examples are:-

- MissingDependency in the solution.xml
- AppModuleComponents for AppModules

This would help minimise changes when unpacked solutions are tracked in git.

**Comment by davidjenni** [comment]
this is a frustration we all share. We have work planned for the next quarter to reduce that diffing noise

**Comment by HansMeiser999** [comment]
It would be great to have something like that. But this a very sensible topic.

I implemented something like this myself before these kind of tools were available for the community. This needs to be implemented very carefully. For example this will change the loading order of scripts associated to forms and most likely break the functionality doing so. This is just one example were such a sorting mechanic might cause problems. 

So right from the start we would need a setting to enable/disable such sorting to bypass any upcoming problems. And please let this setting consume a variable.

**Comment by filcole** [comment]
@SiPurdy  I'm experiencing these issues too.  Totally unsupported, unrecommended, hacks that I've used/suggested are here:

https://github.com/microsoft/coe-alm-accelerator-templates/pull/127
https://github.com/filcole/SolutionRefs

Use at your peril!

**Comment by petrochuk** [comment]
Latest version of solution packager libraries apply sorting
