### ISSUE TITLE
ExcludeFiles option in PowerPlatformChecker does not exclude the file from being checked

### ISSUE THREAD

**Issue by JohannesBertens** [microsoft/powerplatform-build-tools#169]
ExcludeFiles option, does not exclude the file from the scanner:

![image](https://user-images.githubusercontent.com/315946/184864839-833c2968-5b55-4ccd-8106-1970a880c6ff.png)

Gives:
![image](https://user-images.githubusercontent.com/315946/184865056-fa1fd4c4-a820-4626-9e6b-989ad82e15fd.png)

All in that one .msapp file.

**Comment by davidjenni** [comment]
@JohannesBertens  Both the PP-BT task and the underlying pac CLI simply pass through the FilesToExclude expression to the Checker API. The original intent of that parameter was to pass in a filter on the .js level. Not clear if the current API implementation is able to honor excluding a whole CanvasApp from the check? We have an internal thread with the API owners ongoing.

CC: @JesseParsons

**Comment by JohannesBertens** [comment]
Sadly this fails the whole checker task, even though the rest of my solutions are fine.
Being able to exclude the App or the whole Solution would help

**Comment by JesseParsons** [comment]
This is now deployed worldwide, @JohannesBertens please give it a try and let us know if that worked for you.
