### ISSUE TITLE
Download Portal does not have option to exclude tables

### ISSUE THREAD

**Issue by craig-lund** [microsoft/powerplatform-build-tools#170]
The PAC CLI download portal includes.

       --excludeEntities           Comma separated list of entity logical names to exclude downloading (alias: -xe)

This is a huge security risk as site settings such as "Authentication/OpenAuth/Microsoft/ClientSecret" that contain secret values would be stored in source control.

**Comment by davidjenni** [comment]
@craig-lund Agreed, but the --excludeEntities seems a tad too low-level and puts too much responsibility on the prodev running pac CLI and or the CI/CD task.

We need to discuss internally on how to best address the scenario you point to: How to filter efficiently for secrets on download

CC: @ameyaapte1 @kkanakas

**Comment by craig-lund** [comment]
I am working on additions to .gitignore that will block from source control. Ill follow up if I find a work around. Thanks!

**Comment by craig-lund** [comment]
Implemented and tested a work around by adding to the .gitignore file. 

`# Added to block site settings in source
[Ss]itesetting.yml`

**Comment by davidjenni** [comment]
fixed in #186

**Comment by davidjenni** [comment]
shipped in latest PP-BT 2.0.7, see: https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.PowerPlatform-BuildTools
