### ISSUE TITLE
Download Portal fails on adx_blog table

### ISSUE THREAD

**Issue by craig-lund** [microsoft/powerplatform-build-tools#171]
Downloading: Site Setting [adx_sitesetting]...
Downloaded: Bot Consumer [adx_botconsumer]
Downloading: URL History [adx_urlhistory]...
Downloaded: Site Setting [adx_sitesetting]
Downloading: Web Template [adx_webtemplate]...
Downloading: Web File [adx_webfile]...
Downloaded: URL History [adx_urlhistory]
Downloaded: Table Permission [adx_entitypermission]
Downloading: Web Page Access Control Rule [adx_webpageaccesscontrolrule]...
Downloaded: Website Language [adx_websitelanguage]
Downloaded: Web Template [adx_webtemplate]
Downloaded: Web File [adx_webfile]
Downloading: Ad [adx_ad]...
Downloading: Poll [adx_poll]...
Downloading: Website Access [adx_websiteaccess]...
Downloading: Website Binding [adx_websitebinding]...
Downloading: Page Template [adx_pagetemplate]...
Downloaded: Ad [adx_ad]
Downloaded: Poll [adx_poll]
Downloaded: Website Binding [adx_websitebinding]
Downloaded: Page Template [adx_pagetemplate]
Downloading: Ad Placement [adx_adplacement]...
Downloading: Poll Placement [adx_pollplacement]...
Downloaded: Web Page Access Control Rule [adx_webpageaccesscontrolrule]
Downloading: Shortcut [adx_shortcut]...
Downloading: Redirect [adx_redirect]...
Downloading: Web Role [adx_webrole]...
Downloaded: Redirect [adx_redirect]
Downloaded: Shortcut [adx_shortcut]
Downloaded: Ad Placement [adx_adplacement]
Downloaded: Website Access [adx_websiteaccess]
Downloaded: Web Role [adx_webrole]
Downloaded: Poll Placement [adx_pollplacement]
Microsoft PowerPlatform CLI
Version: 1.17.4+g2bdb4f2

Error: ************ Exception getting metadata info from Dataverse   : Failed to resolve entity metadata for adx_blog.

**Comment by craig-lund** [comment]
Tried using custom script that actually gets the latest and work. 
Installing Power Platform CLI Tools...

Name                           Version          Source           Summary                                               
----                           -------          ------           -------                                               
Microsoft.PowerApps.CLI        1.17.5           nuget.org        This package contains the Microsoft PowerPlatform CLI.

This version, or my custom script works.

**Comment by craig-lund** [comment]
Looks like Microsoft.PowerApps.CLI 1.17.5 does not download the adx_blog table. Whereas Microsoft.PowerApps.CLI 1.17.4 tries to download.

**Comment by davidjenni** [comment]
PP-BT tasks have been published to VS Marketplace as 2.0.4
![image](https://user-images.githubusercontent.com/3200210/184960615-513e402c-bf7d-4f9e-bf40-0754fea704b9.png)
