### ISSUE TITLE
Portal Download fails because file exist. No overwrite option available

### ISSUE THREAD

**Issue by craig-lund** [microsoft/powerplatform-build-tools#175]
Missing overwrite option on portal download

> [ 'Microsoft PowerPlatform CLI' ]
> [ 'Version: 1.17.5+gcbb58e8' ]
> [ '' ]
> [ 'Error: File \\\\?\\D:\\a\\1\\s\\portalSrc\\*******\\website.yml already exist. provide -o true argument to overwrite the content' ]
> [ '' ]

--overwrite                 Portal website content to overwrite (alias: -o)

**Comment by davidjenni** [comment]
@craig-lund I'm looking for opinions:
- when designing the `pac paportal download` verb, the feature team was adamant to not overwrite by default in the inner-dev-loop when a dev directly uses the pac CLI.
- I do propose that in the CI/CD scenario like here, the intent is to ALWAYS overwrite, so my hypothesis is, pretty much anyone using the `Power Pages Download` task will always want to overwrite,

CC: @kkanakas @ameyaapte1 @ashishchoudhary001 

There is a related issue in our VSCode extension's issue tracker, which is about the inner-dev-loop scenario: microsoft/powerplatforms-vscode#264

**Comment by craig-lund** [comment]
@davidjenni I agree that default action should be to NOT overwrite. 

- As you suggest I am using this in enterprise CI/CD scenarios. As development is made to a portal each iteration would need to be added to source for promotion to the next environments. 
- Now on the other hand, the portal download is additive only. If you remove a record, it will not be removed from source until you delete the source portal folder and then re-download. Same as removing Solution components. 

Ultimately, it should be an option. Using PowerShell in-between tasks can check if components are removed and chose to delete the source or not. For me, I would want the choice rather than have it made for me. Because when you delete the source there is other considerations. Such as the deployment-profiles folder would need to be added back after the download. 

I am working through my list of issues first and then I will start adding suggested enhancements. I use these tools hundreds of times a day so...

Hope that helps.

**Comment by ameyaapte1** [comment]
We will be supporting the overwrite flag in the upcoming release I'm working on the required changes, we still don't plan to make overwrite true by default although this can be discussed one more time in context of CI/CD

**Comment by craig-lund** [comment]
@ameyaapte1 that is great to hear. I agree that it should be false by default but have the option. I have not seen where deletions don' happen with portals but made the assumption it was working just as the solution unpack was. I will keep an eye out for any errors. 
Thanks!

**Comment by craig-lund** [comment]
As #264 is indicating the delete in not working. I will look into testing when I can but seems like it's not working as expected.
