### ISSUE TITLE
On prem install fails

### ISSUE THREAD

**Issue by NTGerton** [microsoft/powerplatform-build-tools#177]
On prem install fails with... "Permission section could not be loaded" No other information is provided. I had installed the prior, deprecated version and was starting to use it. I uninstalled the prior version to see if that would help...it did not. Now I cannot continue with my pipeline construction since I have no build tools installed. Please help...troy
![install fail](https://user-images.githubusercontent.com/111578147/185668520-e3a84bc8-6b01-4983-af05-747b3193d2be.png)

**Comment by davidjenni** [comment]
@NTGerton the metadata for our PP-BT v2 still allows download and deployment to onPrem AzDO/VSTS.
If you're on a corporate network, this looks more like an networking/permission issue?
Or AzDevOps/VSMarketplace had a hiccup?

I can download the PP-BT:
![image](https://user-images.githubusercontent.com/3200210/185683333-ad5e7bce-812f-4a71-9370-4e5aefbb9121.png)

**Comment by davidjenni** [comment]
@NTGerton thanks for working around. I'm still not sure if this was/is a VS Marketplace hiccup? I've double-checked, our extension's manifest does still allow for AzDO and TFS/OnPrem:
https://github.com/microsoft/powerplatform-build-tools/blob/521e92d75a7dd66c08b32058a80f367fdf93a33f/extension/extension-manifest.json#L11

https://docs.microsoft.com/en-us/azure/devops/extend/develop/manifest?view=azure-devops#installation-targets

**Comment by NTGerton** [comment]
Hi David, nope, no problem with VS Marketplace.  After the workaround was run, I successfully installed the extension from the marketplace.

***@***.***

**Comment by bmaster** [comment]
I'm trying to upgrade to 2.0.5 on our on-prem DevOps, but having the same issue with the install.  I can't find the link to download the VSIX.  Is this still available somewhere?

**Comment by NTGerton** [comment]
@bmaster you have to goto the marketplace outside of your on-prem server to see the download option...

https://marketplace.visualstudio.com/acquisition?itemName=microsoft-IsvExpTools.PowerPlatform-BuildTools

![image](https://user-images.githubusercontent.com/111578147/190423946-97dd558e-4687-42a7-8c74-640057ee0158.png)
