### ISSUE TITLE
PP Import Solution V 2.*

### ISSUE THREAD

**Issue by tiemar** [microsoft/powerplatform-build-tools#179]
I changed the import Version to V2. 
Now after some time receive this error:
Around 80 Minutes the import fails, seems it looses the connection while importing?

Processing asynchronous operation... execution time: 01:17:15 and 42.9202249592593% complete
Microsoft PowerPlatform CLI
Version: 1.17.5+gcbb58e8

Error: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Bearer authorization_uri=https://login.microsoftonline.com/975d243a-4e65-46df-b77f-8f73a893ca23/oauth2/authorize, resource_id=https://perigroup-integration.crm4.dynamics.com/'.
    The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Bearer authorization_uri=https://login.microsoftonline.com/975d243a-4e65-46df-b77f-8f73a893ca23/oauth2/authorize, resource_id=https://perigroup-integration.crm4.dynamics.com/'.
        The remote server returned an error: (401) Unauthorized.

**Comment by tiemar** [comment]
Just to mention. Setting back to V 0 works. 
So we need to use this version still even though the warning appears.

**Comment by davidjenni** [comment]
@tiemar  my bug hypothesis is, the accessToken is not being refreshed? Are you using appId/clientSecret authentication for the task?

**Comment by tiemar** [comment]
@davidjenni No actually we did not have the chance to change the connections. We still use User/PWD.

**Comment by davidjenni** [comment]
@tiemar thanks for getting back. With username/pw authN, pac CLI should be able to re-acquire a new access token, we're investigating on our side why that is not the case

AB#2894540

**Comment by tiemar** [comment]
Ok Thank you.  I Now managed to switch to CLient/Secret but it is the same issue. After 60 Minutes it loses the Connect:
Processing asynchronous operation... execution time: 00:59:31 and 33.0657923472222% complete
Microsoft PowerPlatform CLI
Version: 1.17.5+gcbb58e8

Error: The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Bearer authorization_uri=https://login.microsoftonline.com/975d243a-4e65-46df-b77f-8f73a893ca23/oauth2/authorize, resource_id=https://perigroup-integration.crm4.dynamics.com/'.
    The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The authentication header received from the server was 'Bearer authorization_uri=https://login.microsoftonline.com/975d243a-4e65-46df-b77f-8f73a893ca23/oauth2/authorize, resource_id=https://perigroup-integration.crm4.dynamics.com/'.
        The remote server returned an error: (401) Unauthorized.

I now added Tool V0 and V2 and use only the import Step with V0. I hope that might work using a mixed scenario until it might be fixed.

**Comment by davidjenni** [comment]
@tiemar the fix has been released as PP-BT v2.0.5 to VS Marketplace; it should shortly propagate to the different AzDevOps orgs. Should this still repro, please do verify that the running task is indeed v 2.0.5
