### ISSUE TITLE
Configurable polling interval for asynchronous operation status while overwriting old status line

### ISSUE THREAD

**Issue by HansMeiser999** [microsoft/powerplatform-build-tools#196]
The spam of operation status log entries is really annoying. We are having customers were solution import and upgrade are taking several hours. A four second polling interval for the status update is not necessary. 

Therefore I would really appreciate either of both of two solutions:
1) Overwrite the last status line entry with the new one. The values changing in the same line would still indicate its alive.
2) A configurable setting for the interval to poll for the current status. If it takes like 3 hours to import and upgrade a big solution I really would like to not poll for it every 4 seconds. This adds up to 900 lines of status log lines for just one hour.

**Comment by davidjenni** [comment]
@HansMeiser999 yes, on long-running tasks, the progress reporting is creating way too much noise.
We'll discuss how to improve that while still showing processing progress. 
Ideally, we'd like to avoid asking the pipeline authors to have to manage the polling timeout, so nr 2 above is NOT our favorite...

AB#2924286

**Comment by petrochuk** [comment]
this issue is fixed
