### ISSUE TITLE
On-premise Install Failing

### ISSUE THREAD

**Issue by bmaster** [microsoft/powerplatform-build-tools#202]
On-premise install is failing.  I have checked with our network team to confirm nothing is being blocked.  I am looking for the download link for the VSIX to download upload the extension as suggested in Issue [#177](https://github.com/microsoft/powerplatform-build-tools/issues/177), but can't find that.  Please help.

![image](https://user-images.githubusercontent.com/1508216/190216208-d3a999c0-0eec-41c7-8604-e6b96f7f466b.png)

**Comment by davidjenni** [comment]
@bmaster this seems an issue with VS Marketplace itself. Our AzDevOps task extension still has the same metadata as before, still allowing for separate download.
I can partially repro that red error box when I select an AzDevOps where I have no admin rights. But at least, the button still appears:
![image](https://user-images.githubusercontent.com/3200210/190500348-b9c1ab4a-4b23-4a69-bad2-9fdacde25e9a.png)

What I can offer is a workaround: starting with the August refresh 2.0.7 that was published to VS Marketplace earlier today, I'm also publishing the .vsix as a GH release, with the .vsix attached as asset:

https://github.com/microsoft/powerplatform-build-tools/releases/

CC: @kkanakas
