### ISSUE TITLE
Publish always runs into timeout 4 Minutes

### ISSUE THREAD

**Issue by tiemar** [microsoft/powerplatform-build-tools#205]
The publish step generally leads to a timeout.

Publishing All Customizations...
Microsoft PowerPlatform CLI
Version: 1.18.4+g1a00e63

Error: The request channel timed out while waiting for a reply after 00:04:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
    The HTTP request to 'https://xxxxx.crm4.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.47.9489' has exceeded the allotted timeout of 00:04:00. The time allotted to this operation may have been a portion of a longer timeout.
        The operation has timed out

Even though the timeout is set to 0 (infinite) or 10 or 20. The setting does not have any effect. 
So we use continue on error, but its not the best solution. 
Is there a global timeout which ovverrules this setting?

**Comment by tiemar** [comment]
... seems already addressed in #190

**Comment by davidjenni** [comment]
@tiemar yep, dupe to #190

PR #207 will add it for the next monthly refresh
