### ISSUE TITLE
Portal upload not uploading annotations attached to web files.

### ISSUE THREAD

**Issue by craig-lund** [microsoft/powerplatform-build-tools#213]
After downloading portal to a source branch from a dev environment, when uploading to a test environment only 1 of 18 annotations are uploaded. 
![image](https://user-images.githubusercontent.com/54556910/194363860-6d51c8c9-ff48-49b2-825b-8566b56975e6.png)
![image](https://user-images.githubusercontent.com/54556910/194363896-2b56b6a5-ecd4-4ec3-a030-8b661ca9f962.png)

This is the second pass update 
![image](https://user-images.githubusercontent.com/54556910/194363988-593e777b-64f6-477c-a9c1-e28c993db6b1.png)

Results after
![image](https://user-images.githubusercontent.com/54556910/194364499-a732f3e5-23f3-4d78-952f-78e3aa59a99e.png)

**Comment by craig-lund** [comment]
Developed a workaround. 
Using the Data export and import tasks. added "adx_webfiles; annotations" to the schema file with fetch. Using this tooling the annotations are added and referenced. I added these tasks after the portal upload. 

Additional note: Using the Field Service portal.

**Comment by MrRishabhJain** [comment]
@craig-lund we are actively looking into this and will update you based on our findings.

**Comment by craig-lund** [comment]
Thanks, I am out of country now, Plese let me know how I can support this effort after the 23rd of October.

Sent from Surface Duo
________________________________
From: Rishabh Jain ***@***.***>
Sent: Wednesday, October 19, 2022 2:16:37 AM
To: microsoft/powerplatform-build-tools ***@***.***>
Cc: Craig Lund ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/powerplatform-build-tools] Portal upload not uploading annotations attached to web files. (Issue #213)


@craig-lund<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcraig-lund&data=05%7C01%7Ccraig.lund%40avanade.com%7Ce6050296cdaf45a217ad08dab1aa3eba%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C638017642004726001%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=q%2Bor67G7Xu%2FTWjWR9Y0obM8No5atM%2BfJ5wA1UxwVw54%3D&reserved=0> we are actively looking into this and will update you based on our findings.

**Comment by craig-lund** [comment]
Thanks, I am in Cabo this week. I will check and respond next week.

Sent from Surface Duo
________________________________
From: Rishabh Jain ***@***.***>
Sent: Thursday, October 20, 2022 12:57:32 PM
To: microsoft/powerplatform-build-tools ***@***.***>
Cc: Craig Lund ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/powerplatform-build-tools] Portal upload not uploading annotations attached to web files. (Issue #213)


@craig-lund<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcraig-lund&data=05%7C01%7Ccraig.lund%40avanade.com%7Ceb868463bfed417da37508dab2ccf212%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C638018890576643907%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gXmy%2Fh5yOz%2B%2BpGn1TzdpIRjgbzT6YoI17B5jnzAs1Hw%3D&reserved=0>, looks like the web-file records to which these annotations are trying to get uploaded and attached to, do not exist or are different in the DataVerse. Can you try re-uploading the whole portal again (by deleting the manifest file having the target the Org URL in the name)? That should get the records aligned resolving this issue.

To gain more context, are you trying to upload this data back to the Org from where you downloaded this portal data or is this portal data being migrated to some other Org? Also, if you can share the Org ID(s) with us, we will be able to further analyze the telemetry on the same.

**Comment by MrRishabhJain** [comment]
@craig-lund, were you able to resolve the issue with the aforementioned suggestions, or are you still facing the same issue?

**Comment by MrRishabhJain** [comment]
Hope your issue was resolved. We've not seen any updates on this thread for some time. As a result, we're going to close this issue. If you need any further information or would like to continue the discussion, please feel free to reopen this thread. If the problem persists, please open a new issue.
