### ISSUE TITLE
export and import portal configuration task not available in Azure devops

### ISSUE THREAD

**Issue by devendrapadhi99** [microsoft/powerplatform-build-tools#214]
export and import portal configuration task not available in Azure devops

We need Export and import portal configuration task are required in azure devops pipeline. we already installed power platform build tools but no use, unable to find the export and import configuration tasks

**Comment by devkeydet** [comment]
Do you not see these tasks?
![image](https://user-images.githubusercontent.com/4499296/195058078-1c125924-750d-41fa-885f-c45dd3e02bab.png)

What version of the build tools do you have installed?
![image](https://user-images.githubusercontent.com/4499296/195060005-3bc60bc2-0f0f-431a-90fc-6af87fa0e361.png)

**Comment by davidjenni** [comment]
@devendrapadhi99 if you are on the v2 version of PP-BT, the "Download PAPortal" and "Upload PAPortal" tasks are present, as @devkeydet has in their screenshot.
Please verify you have the v2 version installed in your Azure DevOps org, e.g. for the "Tool Installer" task:

![image](https://user-images.githubusercontent.com/3200210/196560649-6aad0176-ff30-4ad7-ae8c-a0db6ea71266.png)


Or are you referring to the more generic "Export Data" task (which is also part of v2 of PP-BT)?
![image](https://user-images.githubusercontent.com/3200210/196560838-1334adb5-f867-4ed1-a7e9-63e9d36ee884.png)

**Comment by MrRishabhJain** [comment]
Hey @devendrapadhi99, can you confirm if you are able to see these tasks in your ADO org?

**Comment by MrRishabhJain** [comment]
Closing the thread.
