### ISSUE TITLE
'PowerPlatformExportSolution@2' times out or fails when export async is true

### ISSUE THREAD

**Issue by bryansonofpatt** [microsoft/powerplatform-build-tools#215]
Starting on 10/10/22, my export solution task has been timing out. Before this, my solutions were taking 2-5 mins to export, depending on size. Now they are timing out at 60 mins, but should never take that long to export. 
I set the async to false and they export fine. 
I'm running PPT v2.0.7.
Thanks!
Bryan

**Comment by davidjenni** [comment]
@bryansonofpatt That sounds like an issue on the service side. If this still reproes for you, please re-queue your pipeline, but with "Enable system diagnostics" checked when queueing.

From the failing export solution task, please copy/paste just a snippet similar to this one (don't copy the full log for EUII reasons):
The relevant pieces of information we'd need are:
- the task's execution time stamp (UTC)
- the guid for the "Waiting for asynchronous operation <guid>"


```
[ 'Calling pac cli inputs: solution export --name mySolution1 --path D:\\a\\1\\s\\out\\mySolution1 --managed false --async true --max-async-wait-time 60' ]
##[debug]command: D:\a\_tasks\PowerPlatformToolInstaller_8015465b-f367-4ec4-8215-8edf682574d3\2.0.7\bin\pac\tools\pac.exe, first arg of 12: solution
[ 'Connected to...pa-buildtools-test' ]
[ 'Starting Solution Export...' ]
[ 'Waiting for asynchronous operation 04c76851-bf1c-ed11-b83e-0022481c51e4 to complete with timeout of 01:00:00' ]
[ 'Processing asynchronous operation... execution time: 00:00:00 and 0.00582799166666667% complete' ]
[ 'Processing asynchronous operation... execution time: 00:00:04 and 0.121283102777778% complete' ]

```

**Comment by alanrroberts** [comment]
Hi, I am experiencing this as well.

Log snippet looks like this for a run kicked off at 15:30 UTC (some values obscured with xxxx)

```
[ 'Calling pac cli inputs: solution export --name xxxx --path /home/vsts/work/1/a\\xxxx.zip --overwrite true --managed false --async true --max-async-wait-time 60' ]
##[debug]command: /home/vsts/work/_tasks/PowerPlatformToolInstaller_8015465b-f367-4ec4-8215-8edf682574d3/2.0.15/bin/pac_linux/tools/pac, first arg of 14: solution
[ 'Connected to...  xxxx' ]
[ 'Connected as ***' ]
[ 'Starting Solution Export...' ]
[ 'Waiting for asynchronous operation a33a1e8c-0d82-ed11-81ad-00224841bcb1 to complete with timeout of 01:00:00' ]
```

Cheers

Alan

**Comment by petrochuk** [comment]
Thanks for reporting. The issue is forwarded to different team who works on solution import
