### ISSUE TITLE
Power portal extension in dev ops fails on Power Portal Download task

### ISSUE THREAD

**Issue by PiotrMichalski1987** [microsoft/powerplatform-build-tools#218]
Hi. I have been struggling with this for couple of hours now. When I execute dev ops pipeline it fails on the task of downloading portal.

![image](https://user-images.githubusercontent.com/43425759/196703912-f0bf8b07-d27b-4e71-9545-895d93315b4e.png)

Extension is being installed successfully, connection is verified with "who am I".

The details of the errors on the task:

![image](https://user-images.githubusercontent.com/43425759/196704025-33a977b0-aac1-47eb-9a2b-6ffd8240397f.png)

The portion that was cut on the screenshot:

"Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: 2c3cfa5d-7676-493d-810d-529054d8a0ac, Exception Type: System.ArgumentNullException"

When command is tested in VS Code it works fine. The portal id is correct.

I found similar problem here:
[https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Error-when-using-Microsoft-Power-Platform...](https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Error-when-using-Microsoft-Power-Platform-CLI-to-download-portal/td-p/1237550)
I have tried the last suggestion and it is still not executing properly.

I hope someone is able to assist me.

Kind Regards
Piotr

PS: I can share full logs for failed pipeline with the person who will be taking look into the issue. Please message me.

**Comment by davidjenni** [comment]
@PiotrMichalski1987 thank you for reporting, the exceptionId you specified should be enough for the Power Pages team to start investigating and fix.
Looking at the call stack, I assume there's missing data in the exported site, causing the ArgumentNullException:

```
0 {"assembly":"mscorlib, Version=4.0.0.0","method":"System.IO.Path.Combine","level":0,"line":0}
1 {"assembly":"bolt.module.paportal, Version=1.18.0.0","method":"bolt.module.paportal.PortalDataExporter.ExportDataForAdxEntities","level":1,"line":0}
2 {"assembly":"bolt.module.paportal, Version=1.18.0.0","method":"bolt.module.paportal.PortalDataExporter.ExportDataForAllEntities","level":2,"line":0}
3 {"assembly":"bolt.module.paportal, Version=1.18.0.0","method":"bolt.module.paportal.PortalDataExporter.DownloadData","level":3,"line":0}
4 {"assembly":"bolt.module.paportal, Version=1.18.0.0","method":"bolt.module.paportal.verbs.PAPortalDownloadVerb.Execute","level":4,"line":0}
```

AB#2989636

CC: @ameyaapte1

**Comment by PiotrMichalski1987** [comment]
Thank you for quick response. 

Kind Regards
Piotr

**Comment by davidjenni** [comment]
@PiotrMichalski1987 one possible work around, after I took a closer look at your screenshot:

Your download task has the "Download path" task input property assigned with: `c:\paportal`

While this might work locally, this can and is problematic in an Azure DevOps build agent's context, since tasks are generally expected to only access paths within the drive that holds the repository. Best practice for tasks is to NOT specify specific OS drives (e.g. `c:\` in your example), but instead use relative paths (which are assumed relative to the repo's src directory), or use predefined AzDO variabled (https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services) like `$(Build.SourcesDirectory)` or similar.

**Comment by PiotrMichalski1987** [comment]
I have tried to follow best practice as suggested (thank you for the link) and modified my task:

![image](https://user-images.githubusercontent.com/43425759/196938407-ee3b3c4b-33ad-4304-b11e-8d9711e310ea.png)


However, the error still persists:

![image](https://user-images.githubusercontent.com/43425759/196938476-2a0aab27-3260-4ea8-90e8-29961afab944.png)

[Exception Id: 12cdc9d4-7405-402a-aefc-53d0e0afbd02, Exception Type: System.ArgumentNullException]

**Comment by davidjenni** [comment]
@PiotrMichalski1987 The folder `$(Agent.WorkFolder)` would not be my first choice, since that folder is not guaranteed to be writable and can also risk clobbering folders that the build agent requires; from the docs:
> Note: This directory is not guaranteed to be writable by pipeline tasks (eg. when mapped into a container)

I'd recommend e.g. `$(Build.SourcesDirectory)\downloads` or similar. But at least on my Az DevOps pipeline, writing to Agent.WorkFolder does work, so my error hypothesis is, the NullRef is caused by pot. inconsistent data in your Power Pages within your website.
But to state the obvious, this should still not cause a FastExit error, but instead at least return a more actionable error message.

CC: @ameyaapte1 @MrRishabhJain

**Comment by PiotrMichalski1987** [comment]
Thank you for looking into the issue and trying to solve the problem and also for all suggestions. I have just tried to use $(Build.SourcesDirectory)\downloads :
![image](https://user-images.githubusercontent.com/43425759/197223611-77becc22-a318-4d78-982f-2adf2e38626e.png)

![image](https://user-images.githubusercontent.com/43425759/197223221-4f21fd92-c07b-45cd-a488-2175ba30f55f.png)
Sadly the same exception is being thrown. 

The difference I see now is that red error messages are missing text:
![image](https://user-images.githubusercontent.com/43425759/197222689-4e418146-166f-499c-815e-e99961034173.png)

The website that I have created is standard Power Portal with two custom pages, it is PWA enabled, contains chatbot and requires AD authentication. 
The only strange behaviour I have noticed about it is that when I modify value in Portal Management app to disable redirect to profile page after authentication it is still redirecting to profile page. 

I did some extra tests, and I can confirm, I am able to execute the CLI on Visual Studio Code for the same website without any problems.
Additionally, I have tried to download different portal on the same environment and effect after executing pipeline is the same.
![image](https://user-images.githubusercontent.com/43425759/197227748-4156c213-e952-4aef-af6f-638ec8f1498d.png)

Is there anything else you would like to know about the portal that could potentially help, or you would like me to check anything?

Kind Regards
Piotr

**Comment by MrRishabhJain** [comment]
@PiotrMichalski1987 we were unable to pin down the issue with the stack trace found in the telemetry. Requesting you to please share your log file with us.

**Comment by PiotrMichalski1987** [comment]
Hello, 

@davidjenni 

The version of the extension installed for VS Code is :
![image](https://user-images.githubusercontent.com/43425759/197519713-38e72683-c1a0-4d96-b3a2-767116c58afe.png)

When executing pac tools the result is following:
![image](https://user-images.githubusercontent.com/43425759/197519832-82971f4d-50ce-4b40-8430-9f559e5aa373.png)

The version info on the task PowerPlatformDownloadPaportal is:
![image](https://user-images.githubusercontent.com/43425759/197520147-9b7fe565-4470-4b5f-849a-bb722744ba8c.png)

Power platform installer and "who am I" are using the same version as above 2.0.8 .

Yes, you are right, the authentication method differs. On VS Code I have used interactive username/password authN , when creating authentication profiles. On DevOps I needed to create Power Platform Service Connection using the form below to be able to authenticate when requesting access:

@MrRishabhJain I am attaching logs to this message,
[logs_1244.zip](https://github.com/microsoft/powerplatform-build-tools/files/9851363/logs_1244.zip)

**Comment by MrRishabhJain** [comment]
@davidjenni The logs provided by Piotr are missing the PAC CLI logs. Can you help us with the steps to extract these logs from the pipeline run?

**Comment by davidjenni** [comment]
@PiotrMichalski1987 @MrRishabhJain 
The pac CLI can be located using an existing pipeline variable: `$(POWERPLATFORMTOOLS_PACCLIPATH)\pac\tools\logs` (this path assumes a Windows build agent).
Piotr, please add a task after the Power Portal Download task, with the green marked properties set:
![image](https://user-images.githubusercontent.com/3200210/199050553-7d2abfb7-46af-426d-a8db-5b3393345c27.png)

or in yaml:
```
- task: PublishPipelineArtifact@1
  displayName: 'Publish pac CLI logs'
  inputs:
    targetPath: '$(POWERPLATFORMTOOLS_PACCLIPATH)\pac\tools\logs'
    artifact: 'pac-cli-logs'
  continueOnError: true
  condition: always()
```

**Comment by PiotrMichalski1987** [comment]
@davidjenni @MrRishabhJain 
[pac-cli-logs.zip](https://github.com/microsoft/powerplatform-build-tools/files/9920806/pac-cli-logs.zip)

Hello, I have updated yaml file and I am attaching the artifact produced to this message
