### ISSUE TITLE
Unable to download Power Platform Build Tools from Marketplace

### ISSUE THREAD

**Issue by damiencelle** [microsoft/powerplatform-build-tools#219]
I can't download Power Platform Build Tools from Marketplace. From "Get it free", I have a 500 error.
 
![image](https://user-images.githubusercontent.com/29300377/196919712-37208013-47ad-40a8-9a81-ded07a82e420.png)

**Comment by davidjenni** [comment]
@damiencelle This is a general error with VS Martkeplace. Please contact the marketplace team if this persists.

As a workaround, if your intent is to install into an OnPrem AzDevOps/VSTS instance: the vsix is also available in this repo's release page:

https://github.com/microsoft/powerplatform-build-tools/releases/tag/v2.0.8
