### ISSUE TITLE
Power Platform Import Solution Task From Azure Dev Ops triggers two solutions deploy in CRM

### ISSUE THREAD

**Issue by WaseemAhmedBekaert** [microsoft/powerplatform-build-tools#235]
Power Platform Import Solution Task From Azure Dev Ops triggers an Import into CRM solution. But about an hour later into the Import there is another entry in the solution history of CRM for the same solution. This causes the ADO task to fail.

As seen in the below image there are two entries. The second fails as the first one is still in progress.
![keyntpresent](https://user-images.githubusercontent.com/117186655/199909271-dfbe9fb4-b1fe-48e6-b1cf-eac9c91284ab.PNG)
![Capture](https://user-images.githubusercontent.com/117186655/199909746-224a120e-9cd4-4209-8a6e-9dbb4a49488e.PNG)

**Comment by beumah** [comment]
We have the same issue. It has been happening consistently the last couple of weeks. Right before the actual import succeeds a new import is started, which causes the PipeLine to fail. 
And also the actual error message is not being shown in the logs of the pipeline. 

![image](https://user-images.githubusercontent.com/18741469/202438821-0beee9e1-cb42-49da-9cac-831e78839dcf.png)

**Comment by beumah** [comment]
Hi @davidjenni . Thanks for the update. Unfortunately this update did not resolve the issue for us. We also have an active support ticket (2211070050001559) to which I attached the log files.
