### ISSUE TITLE
Power Platform Export Solution + Upack pass wrong path the CLI

### ISSUE THREAD

**Issue by yveskerwyn** [microsoft/powerplatform-build-tools#241]
Here's the debug info from Power Platform Export Solution:

```
[ 'Calling pac cli inputs: solution export --name PermitManagement --path C:\\a\\1\\aPermitManagement.zip --overwrite true --managed false --async true --max-async-wait-time 60' ]
```

In the above --path should be `C:\\a\\1\\a\\PermitManagement.zip`, not: `C:\\a\\1\\aPermitManagement.zip`

Further debugging with command line script shows that the solution got exported to the directory `c:\a\1` with name `aPermitManagement.zip` instead of `PermitManagement.zip` in subdirectory `c:\a\1\a`:
```
11/14/2022  07:29 PM    <DIR>          .
11/14/2022  07:29 PM    <DIR>          ..
11/14/2022  07:28 PM    <DIR>          a
11/14/2022  07:29 PM           458,631 aPermitManagement.zip
11/14/2022  07:28 PM    <DIR>          b
11/14/2022  07:28 PM    <DIR>          s
11/14/2022  07:29 PM    <DIR>          sPermitManagement
11/14/2022  07:28 PM    <DIR>          TestResults
               1 File(s)        458,631 bytes
               7 Dir(s)  124,677,996,544 bytes free
```

Same problem for the unpacking, as shown when checking the contents of the current directory `C:\a\1\s` - which is empty:
```
11/14/2022  07:28 PM    <DIR>          .git
               0 File(s)              0 bytes
               1 Dir(s)  124,677,996,544 bytes free
```

**Comment by yveskerwyn** [comment]
Actually, I just found out that this is not a bug, but rather a misconfiguration onmy side, because of an error (missing back slash) in the PL-400 Lab instructions, where they forgot to specify the correct input for Solution Output File: $(Build.ArtifactStagingDirectory)$(SolutionName).zip. It should be $(Build.ArtifactStagingDirectory)\$(SolutionName).zip - the back slash was missing.

**Comment by davidjenni** [comment]
@yveskerwyn thanks for following up. If it helps you, I've done the same mis-edits myself. Annoying how long it takes my eyes to detect the missing '/' :-)
