### ISSUE TITLE
Import Stops

### ISSUE THREAD

**Issue by tiemar** [microsoft/powerplatform-build-tools#242]
The import just stops without reason after a certain time which is different every day.
The solution is imported fine into the instance, just the Pipelinestep reports an error. 
It happens only with large Solutions. 

[ '' ]
##[error]error: 1
##[error]failed: Connected to...xxx

Solution Importing...

Processing asynchronous operation... execution time: 01:45:22 and 12.54% complete
Microsoft PowerPlatform CLI
Version: 1.19.4+gfbe2fd6

Error: The given key was not present in the dictionary.

Usage: pac solution import [--path] [--activate-plugins] [--force-overwrite] [--skip-dependency-check] [--import-as-holding] [--publish-changes] [--convert-to-managed] [--async] [--max-async-wait-time] [--settings-file]

Finishing: Power Platform Import Solution

**Comment by scosec** [comment]
Same here. This issue has been around for a few weeks now. Hopefully this will be resolved.
Files are available within the pipeline. So it seems something is wrong within the importer.

**Comment by scosec** [comment]
It appears tho that this issue happens when the solution install fails. Check make.powerapps.com solution history for any messages.

**Comment by rsonnemans** [comment]
Same problem here since Wave2 update.

See issue:  #220

**Comment by tiemar** [comment]
Are there any news on this topic?
