### ISSUE TITLE
pac solution Import fails with error but does not stop script

### ISSUE THREAD

**Issue by craig-lund** [microsoft/powerplatform-build-tools#253]
When running the pac solution import command in a PowerShell script, errors do not fail the script. When using pac solution pack errors do fail the script. 
![image](https://user-images.githubusercontent.com/54556910/205224819-159e50b4-ce61-4877-a19c-3f1676019c9f.png)
![image](https://user-images.githubusercontent.com/54556910/205679664-54fe5ba3-60cd-454d-ab98-0efe91eaf951.png)

**Comment by rpothin** [comment]
Hi @craig-lund,

Can you try to use the [`$?` automatic variable available in PowerShell](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.3#section-1) to detect if there is an error?

You can find an example of implementation I have done [here](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/1603e5df821860ddc671888db00b33544fcdb365/scripts/post-init-setup.ps1#LL495-L500C2).

> Note: In my case I run again the command to get the error it returns because I am catching it in a variable in the first execution.

I hope this idea will help you.
