### ISSUE TITLE
Directory is Empty. Nothing will be added to build artifact 'drop'

### ISSUE THREAD

**Issue by jwstl** [microsoft/powerplatform-build-tools#255]
When running a pipeline the process will complete successfully, however I get a warning in the summary. Looking at the job, this is occuring in the Publish Build Artifacts step.

`##[warning]Directory '/agent/_work/1/a' is empty. Nothing will be added to build artifact 'drop'.`

`trigger:
    - main
    
    pool:
      lxpool
    
    steps:
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          sudo apt-get update && \
            sudo apt-get install -y dotnet-sdk-6.0
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'sudo apt-get install -y aspnetcore-runtime-6.0'
    
    - task: PowerPlatformToolInstaller@2
      inputs:
        DefaultVersion: true
    - task: PowerPlatformWhoAmi@2
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'DevOpsSrvcConn'
    
    - task: PowerPlatformExportSolution@2
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'DevOpsSrvcConn'
        SolutionName: 'PipelineTest'
        SolutionOutputFile: '$(Build.StagingDirectory)\PipelineTest_1_0_0_1.zip'
        AsyncOperation: true
        MaxAsyncWaitTime: '60'
    - task: PowerPlatformUnpackSolution@2
      inputs:
        SolutionInputFile: '$(Build.StagingDirectory)\PipelineTest_1_0_0_1.zip'
        SolutionTargetFolder: '$(Build.SourcesDirectory)\PipelineTest'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'`

**Comment by paulbreuler** [comment]
The path to publish appears to not ever be populated. Each task is using a different directory.
- Exported solution:  SolutionOutputFile: '$(Build.**StagingDirectory**)\PipelineTest_1_0_0_1.zip'
- SolutionTargetFolder: '$(Build.**SourcesDirectory**)\PipelineTest'
- Publishing artifact from: PathtoPublish: '$(Build.**ArtifactStagingDirectory**)'

You would need to put something there such as the exported solution.

SolutionOutputFile: '$(Build.**_ArtifactStagingDirectory_**)\PipelineTest_1_0_0_1.zip'

Publishing artifact from: PathtoPublish: '$(Build.**_ArtifactStagingDirectory_**)'

**Comment by petrochuk** [comment]
This doesn't appear to be Power Platform Build Tools issue
