### ISSUE TITLE
Does Power Platform build tools are compatible with CRM 8.2 on-premises? 

### ISSUE THREAD

**Issue by fatihdurgut** [microsoft/powerplatform-build-tools#256]
Hello Team, 

My customer is using CRM 8.2 on-premises and trying to create a build pipeline but facing the error below. They want me to give an official answer if Power Platform build tools are compatible with CRM 8.2 on-premises. I couldn't find any public documentation for this. 
I'll glad if you can suggest. 

![image](https://user-images.githubusercontent.com/4159116/205567098-a085b558-fcc4-4284-bb75-f7f232c5d9fb.png)

**Comment by BetimBeja** [comment]
Hi @fatihdurgut ,
I don't think these tools are compatible with on-premises environments as they are using the [DataverseClient](https://github.com/microsoft/PowerPlatform-DataverseServiceClient) and it doesn't support on-premises environments. 
While there are community efforts to make `DataverseClient` work with on-premises environments like [this](https://github.com/Data8/DataverseClient), I (community member) am not aware of any plans from Microsoft to implement a similar solution.
