### ISSUE TITLE
Add option to update applications... 

### ISSUE THREAD

**Issue by craig-lund** [microsoft/powerplatform-build-tools#271]
Is it possible when performing application actions to perform updates to applications that are available in Admin > Environments > [Environment Name] > Dynamics 365 apps?

**Comment by petrochuk** [comment]
[pac application](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/application) only supports "list" and "install" at this time

**Comment by parvezghumra** [comment]
@petrochuk Are there plans on the current PAC CLI roadmap to support application updates (using **pac application**)? I have just tried a **pac application install** command for an app that is already installed but an update is available. Here's the output:

![image](https://github.com/microsoft/powerplatform-build-tools/assets/8039551/0d1f8532-7f07-4bc0-aa29-39f4390d186d)

I am trying to automate some of my environment maintenance activity and it would be really help if this would be made possible?

cc: @snizar007 @craig-lund
