### ISSUE TITLE
When adding PowerPlatformSetConnectionVariables@2 to a Task Group, Output Variables section is not available

### ISSUE THREAD

**Issue by mannybellas** [microsoft/powerplatform-build-tools#280]
Expected:

![image](https://user-images.githubusercontent.com/1657903/216910230-cc80a173-6927-458d-b244-05f58e75697e.png)

Actual:

![image](https://user-images.githubusercontent.com/1657903/216910386-af3ca4d6-e765-4e7b-b8d7-b257dc616110.png)

**Comment by tehcrashxor** [comment]
This is an issue with ADO Pipelines in general, nothing we can do about it with our tasks.
Looks like this has been an open issue for a while on the ADO Docs with no response at https://github.com/MicrosoftDocs/azure-devops-docs/issues/6983
