### ISSUE TITLE
Power Platform CLI pack solution does not handle fx formulas (reintroduced error)

### ISSUE THREAD

**Issue by hsvensson1976** [microsoft/powerplatform-build-tools#281]
Running "pac solution unpack" followed by "pac solution pack" on a solution (that imports perfectly by manual export followed by manual import) I get the following error message:

Error: Entity 'X' references formula file '/Formulas/X-FormulaDefinitions.yaml', but file is not included in solution.zip

I am using Microsoft.PowerApps.CLI.1.21.8 for this. It seems like this issue has been reintroduced since the release of 1.20.3.

-----
Copied from comment here: https://powerusers.microsoft.com/t5/Power-Apps-Pro-Dev-ISV/Azure-pipeline-error-with-formula-PowerFX-dataverse-column/m-p/1998045/highlight/true#M8342
(User DavidJen referred to this GitHub project in the same discussion there)

**Comment by petrochuk** [comment]
Fixed in latest build of PAC CLI
