### ISSUE TITLE
PowerPlatformUnpackSolution@2 - Access denied error for NavigationSetting

### ISSUE THREAD

**Issue by NiklasAtAdesso** [microsoft/powerplatform-build-tools#285]
Hey,

I'm having an issue with a "NavigationSetting" component when unpacking the solution using the PowerPlatformUnpackSolution task.

The "NavigationSetting" belongs to the D365 Sales Professional App which has been added to the solution. The pipeline is running on a local TFS.

The error is `'Error: Access to the path \'D:\\{46b58645-a1d9-417f-ad0c-0bb27790c771}.xml\' is denied.'` Without the D365 Sales Professional App inside of the solution, the task works well.

We call the Task using these parameters: 
`- task: microsoft-IsvExpTools.PowerPlatform-BuildTools.unpack-solution.PowerPlatformUnpackSolution@2
  displayName: 'Power Platform Unpack Solution '
  inputs:
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)\$(SolutionName).zip'
    SolutionTargetFolder: '$(Build.SourcesDirectory)\$(SolutionPath)'
    SolutionType: Both`

The Guid inside the error message points to this item of the solution:
`<NavigationSettings>
          <NavigationSetting>
            <NavigationSettingId>{46b58645-a1d9-417f-ad0c-0bb27790c771}</NavigationSettingId>
            <QuickSettingOrder>0</QuickSettingOrder>
            <SettingType>0</SettingType>
            <Privileges>0</Privileges>
            <AdvancedSettingOrder>0</AdvancedSettingOrder>
            <LocalizedNames>
              <LocalizedName description="Standardeinstellungen" languagecode="1031" />
              <LocalizedName description="Standard settings" languagecode="1033" />
            </LocalizedNames>
            <Descriptions>
              <Description description="Organisationsübergreifende Einstellungen konfigurieren" languagecode="1031" />
              <Description description="Configure organization wide settings" languagecode="1033" />
            </Descriptions>
          </NavigationSetting>`

Does anybody have an idea, how to fix this?

Thanks

Niklas

**Comment by cjbadger** [comment]
I'm facing the same issue when using `pac solution unpack` in Windows PowerShell, Developer PowerShell for VS2019 and Developer PowerShell for VS2022. 

The error I'm seeing is identical to the error Niklas reported - including the GUID referenced in the error (46b58645-a1d9-417f-ad0c-0bb27790c771).

PowerPlatform CLI version: 1.21.8+ga93a2c3
PowerShell version: 5.1.22000.1335

**Comment by tehcrashxor** [comment]
Looks like this bug was introduces into SolutionPackager in the Nov 2020 release of the [Microsoft.CrmSdk.CoreTools v9.1.0.64 nuget package](https://www.nuget.org/packages/Microsoft.CrmSdk.CoreTools/9.1.0.64), and we've just not heard from anyone hitting it in all that time.

Tracking internally as Bug AB#3329138 : SoPa writes to root directory when unpacking app modules

**Comment by tehcrashxor** [comment]
Fix released in the downstream stages - SolutionPackager.exe in [Microsoft.CrmSdk.CoreTools v9.1.0.146](https://www.nuget.org/packages/Microsoft.CrmSdk.CoreTools/9.1.0.146) and pac CLI via [Microsoft.PowerApps.CLI v1.22.3](https://www.nuget.org/packages/Microsoft.PowerApps.CLI/1.22.3)

Fix for Power Platform Build Tools is in #307, which we'll be deploying Monday.

**Comment by tehcrashxor** [comment]
Fix released as [v2.0.19](https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.PowerPlatform-BuildTools)
