### ISSUE TITLE
Azure Pipeline- Error when importing solution via pipelines

### ISSUE THREAD

**Issue by ahmadnazrinshah** [microsoft/powerplatform-build-tools#286]
Hi,
I have a YAML pipeline that will handle deployment process. 
However, right now there is an issue when importing the solution.

The reason given was: Solution manifest import: FAILURE: Object reference not set to an instance of an object.
Microsoft PowerPlatform CLI
Version: 1.21.5+ge089c16

Error: The async operation completed with a statuscode of Failed

Can anyone advise what need to be done here?

**Comment by petrochuk** [comment]
> Hi, I have a YAML pipeline that will handle deployment process. However, right now there is an issue when importing the solution.
> 
> The reason given was: Solution manifest import: FAILURE: Object reference not set to an instance of an object. Microsoft PowerPlatform CLI Version: 1.21.5+ge089c16
> 
> Error: The async operation completed with a statuscode of Failed
> 
> Can anyone advise what need to be done here?

Can you send solution.zip file?
