### ISSUE TITLE
Unexpected Error when importing solution using 2.0.17

### ISSUE THREAD

**Issue by KristianKlodeD** [microsoft/powerplatform-build-tools#291]
After yesterdays update form 2.0.16 to 2.0.17 none my my pipeline usin powerplatofrm build tools 2.X is working when importing a solution.
It only gives this generic error as shown below.
![image](https://user-images.githubusercontent.com/128026855/225545682-3d02d340-2761-4402-a89d-39e6e514201b.png)

Nothing was changed besides the version. @tehcrashxor do you know what could have changed that will give the above error?

**Comment by tehcrashxor** [comment]
The only change in 2.0.17 was an Icon update,
@KristianKlodeD, is the pipeline still failing?  Does it repro in the latest 2.0.18 release?

**Comment by darrenbayliss-dev** [comment]
I am getting the same error importing on 2.0.18, it worked ok on all previous versions. The import starts runs for between 1-2  mins and fails with 'The reason given was: An unexpected error occurred.'.

**Comment by sunilsbs** [comment]
I am also getting the similar error. Can someone help on this. The same set up runs fine on other solutions or repo. but for this one it gives error, No clue what i am missing.
```
Solution Importing...
  Microsoft PowerPlatform CLI
  Version: 1.21.8+ga93a2c3
  
  Error: An unexpected error occurred.
      An unexpected error occurred.
  
  
  Usage: pac solution import [--path] [--activate-plugins] [--force-overwrite] [--skip-dependency-check] [--import-as-holding] [--publish-changes] [--convert-to-managed] [--async] [--max-async-wait-time] [--settings-file]
```

**Comment by larhem** [comment]
Our problem was access to key vault that was reffereed to in our deploymentsettings file. 
It has been an update to what access is needed and how access must be configured on key vaults that are accessed during import of solution

**Comment by darrenbayliss-dev** [comment]
remove any references to key vault from powerplatform also make sure you install the tools '- task: PowerPlatformToolInstaller@2'

**Comment by sunilsbs** [comment]
Thank you everyone. Solution got imported to target environment. We had some issues with deployment settings file, where it had some extra or missing variables.
Thanks!

**Comment by JawnLegend** [comment]
I'm getting the same error on the import solution task with my deployment settings file. How did you fix this? I've double-checked, and none of the connection references and environment variables are blank.

**Comment by INC02203** [comment]
@JawnLegend Are you using connection references in your solution? If yes, did you share those connections (target environment) with the service principal app?

Thanks!

**Comment by JawnLegend** [comment]
Hi, yes that did seem to solve it - thanks! However, another issue occurs now. It doesn't seem as if my environment variable gets updated between the environments when I migrate with the pipeline. Anyone else experiencing this?
