### ISSUE TITLE
Use of unpacked unmanaged code for deployment??

### ISSUE THREAD

**Issue by sanjeev40084** [microsoft/powerplatform-build-tools#294]
Almost all the examples that I have seen for power platform regarding ci/cd goes somewhat in this order:
- export and unpack unmanaged code from dev environment 
- check in code in source control
- pack unpacked unmanaged code from source control
- import packed unmanaged code in build env
- download managed solution from build env
- deploy downloaded managed solution to target env

This works however one thing I never understood is why we are using unmanaged code in first place. It makes sense for source control but for deployment instead of packing unmanaged code, importing then downloading managed solution if we could unpack managed solution, put it in source control, pack managed solution and deploy the packed managed solution wouldn't that would save time importing unmanaged solution and then exporting managed solution step from above?

It wud look something like this:
- export and unpack both unmanaged and managed solution from dev environment 
- check in both solutions code in source control
- pack unpacked managed solution code from source control
- deploy managed solution to target env

Do let me know if I am missing something from the process I suggested??

Thanks,
Sanjeev

**Comment by erofee** [comment]
Hi Sanjeev,

One thing that using a build environment does, is tests the import process against an environment that should mirror your production environment.

This would catch a missing dependency before the build hits your release pipeline.

Does it make a big difference?  Not really.  Neater release pipeline I suppose 🤷‍♀️

**Comment by petrochuk** [comment]
This feedback goes outside of these build tools. I'll pass it along to Power Platform team
