### ISSUE TITLE
Export Solution Fails when a Solution-aware Power BI Report/Dataset is included

### ISSUE THREAD

**Issue by erofee** [microsoft/powerplatform-build-tools#298]
When trying to export a solution with a Power BI Report/Dataset that is solution-aware, the following error is thrown:
`[ 'The reason given was: Your solution could not be exported. Sign in to your Power BI account, then give it another go.' ]`

I have tested manually exporting the solution, and this works.

![image](https://user-images.githubusercontent.com/1436346/230559909-f8113f33-5c78-42fa-8000-26323703221e.png)

**Comment by jens-voigt** [comment]
Same issue here

**Comment by jsprehe** [comment]
Same issue here. Any resolution or fix available?

**Comment by ElliottHulburdNTT** [comment]
If you are using a service principal to, I was able to get past this error by following steps 4 and 5 in here https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal , however I then get another error 'The reason given was: That action didn't work out, to keep going upgrade your Power BI account on a free trial.'

**Comment by EHulburd** [comment]
I was able to get past this error by following steps 3 and 4 here [(https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal] , however I then get another error about licensing '_The reason given was: That action didn't work out, to keep going upgrade your Power BI account on a free trial_.'

**Comment by petrochuk** [comment]
@erofee

Can you provide steps you do to build this solution?

**Comment by simoninnyc** [comment]
I'm also experiencing the same issue. I added the Service Principal to my workspace following Step 4 [here](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal)  but I don't have permission to enable the Power BI service admin setting (Step 3). This is a blocker to getting my solution put into DevOps and is highly frustrating.

**Comment by sam-barrett-synsci** [comment]
Are there any updates? I am also encountering the error 'The reason given was: That action didn't work out, to keep going upgrade your Power BI account on a free trial' in the devops pipeline step.

I have a solution aware workspace and all of the Power BI components in my Power Platform solution. I have enabled organization-wide permissions on just about every Power BI setting for good measure and setup all of the steps from the MS documentation.

**Comment by Niels-SL** [comment]
I keep getting this error. 

I have tried assigning a license to the Service Principal as well, but it doesn't work.

**Comment by JakeStratton** [comment]
We are also having the same issue for about a week now.

**Comment by sdhsynsci** [comment]
@petrochuk We are also stuck at this same juncture.  We have a go live this weekend for a large model driven application using powerbi inside of the model driven app.  This has derailed the entire plans for go live.  What additional informaiton can we provide to get a workaround or solution to this problem.  We have tried all of  the above steps and are stuck on pac - Clone or Sync solution step when running the sport_solution_to_git from AA4PP. Asynchronous operation 5d49d37e-5631-ee11-bdf3-000d3a32af20 failed within 00:01:10.3074045.

The reason given was: That action didn't work out, to keep going upgrade your Power BI account on a free trial.
Microsoft PowerPlatform CLI
Version: 1.25.5+g24fc1f8
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: The async operation completed with a statuscode of Failed.

**Comment by Niels-SL** [comment]
Has anyone come any further with this issue?

**Comment by sdhsynsci** [comment]
@Niels-SL  After much wasted time and many support calls.  This is not supported, it is all preview functionality.  Until it is GA and support is added into pipelines and ALM, it is best not to use this in any production system.  In Fact, we have found it is easier to just revert to doing reporting using the SSRS approach with fetch xml and the standard reporting.  It is also much faster than waiting for the Power BI datasets and reports to load.

**Comment by petrochuk** [comment]
I am closing this issue as external
