### ISSUE TITLE
The PowerPlatformImportSolution@2 task doesn't activate plugins (publish workflows)

### ISSUE THREAD

**Issue by vkhmialnitski** [microsoft/powerplatform-build-tools#301]
Looks like after the update to 2.0.18 we are getting false every time "--activate-plugins false".
It's just ignoring the input parameter "ActivatePlugins" ##[debug]ActivatePlugins=True

**Comment by tehcrashxor** [comment]
This code has not changed for over six months, but it is explicitly looking for `true` not `True`
Tracking the case sensitivity issue with AB#3306135, but setting it to lowercase should solve your issue.
