### ISSUE TITLE
Error: Cannot find required file 'Customizations.xml'.

### ISSUE THREAD

**Issue by ITAndy23** [microsoft/powerplatform-build-tools#313]
Getting error during Power Platform Pack Solution using Azure Devops Online:
2023-04-21T21:25:58.6597900Z ##[error]error: 1
2023-04-21T21:25:58.6612720Z ##[error]failed: 
Packing Solution...

Packing D:\a\r1\a\ProjectName\solutions\dev_solution to D:\a\r1\a\$(Build.StagingDirectory)\ProjectName_managed.zip

Microsoft PowerPlatform CLI
Version: 1.21.13+g348c5e9

Error: Cannot find required file 'D:\a\r1\a\ProjectName\solutions\dev_solution\Other\Customizations.xml'.

Steps are:
Init job
Download artifact
Power Platform Tool Installer
Power Platform Pack Solution (Error happens here)
Power Platform Checker
Power Platform Import Solution
Power Platform Publish Customizations

I am able to manually export the solution from my dev environment and import into the sandbox and production environments.

**Comment by petrochuk** [comment]
It looks like your folder '....ProjectName\solutions\dev_solution' doesn't have unpacked solution files
