### ISSUE TITLE
Missing Releases / Release Notes

### ISSUE THREAD

**Issue by fowl2** [microsoft/powerplatform-build-tools#326]
It appears that version 2.0.25 was deployed to Azure Devops yesterday, likely as a result of https://github.com/microsoft/powerplatform-build-tools/pull/325, but the [last GitHub release](https://github.com/microsoft/powerplatform-build-tools/releases/tag/v2.0.8) was a very long time ago in October 2022, is 2.0.8

```
2023-05-26T04:46:08.1106921Z Task         : Power Platform Import Solution
2023-05-26T04:46:08.1106999Z Description  : Power Platform Import Solution
2023-05-26T04:46:08.1107078Z Version      : 2.0.25
```

```
2023-05-25T11:58:23.0672466Z Task         : Power Platform Import Solution
2023-05-25T11:58:23.0672543Z Description  : Power Platform Import Solution
2023-05-25T11:58:23.0672624Z Version      : 2.0.19
```

Could we please have timely releases/release notes?

**Comment by devkeydet** [comment]
Release notes are published to the Azure DevOps Marketplace.
https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.PowerPlatform-BuildTools
![image](https://github.com/microsoft/powerplatform-build-tools/assets/4499296/220854da-a42a-4cb6-a4fa-5cc78efb2e3c)

Based on your link, I think what you are asking for is to have the same information that is published to marketplace show up is individual [releases ](https://github.com/microsoft/powerplatform-build-tools/releases)in the [releases ](https://github.com/microsoft/powerplatform-build-tools/releases)section here on GitHub.  Yes?

**Comment by fowl2** [comment]
Yes, that'd be great - once you start you can't stop! :)

Ideally they be included or at least links somewhere prominent in the [docs](https://learn.microsoft.com/en-us/power-platform/alm/devops-build-tools), given that's where the logs and in-product links go, and actually finding this repo was a bit a journey.

**Comment by fowl2** [comment]
PS. the "Power Platform Actions" (for GitHub) [do post GitHub Releases](https://github.com/microsoft/powerplatform-actions/releases). Seems a little bit of duplicated effort there?
