### ISSUE TITLE
power platfrom import solution having issue with parallel jobs 

### ISSUE THREAD

**Issue by PuneethPuni** [microsoft/powerplatform-build-tools#331]
Hi Team, 

Using the self-hosted servers(2core CPU) we are running the 3 paralle power platfrom import jobs. We have observed that, one of the jobs not imported the solution into the environment even though it states as successful. And we can see the solution has imported 2 times in other environments. We have checked the connection strings, all are configured correctly.

**Comment by petrochuk** [comment]
Are you using your own hosted pool of Azure DevOps agents? Can you provide more detailed error?

**Comment by PuneethPuni** [comment]
@petrochuk, sorry for the delay. Yes we are using the self hosted azure DevOps agents. and credentials userd for 3 environmants are some.
