### ISSUE TITLE
PowerPlatformExportSolution Workflow export: FAILURE when solution contains a modern flow

### ISSUE THREAD

**Issue by cryptasian** [microsoft/powerplatform-build-tools#334]
When using Power Platform Build Tools to export a solution through DevOps, any solution that contains a modern flow (PowerAutomate flow), fails.

The most recent test was on a solution that only contained a modern scheduled flow that would simply initialize a variable. The error message said: 
[ 'The reason given was: Workflow export: FAILURE, workflow id {c653a214-2cf0-ed11-8849-00224803def2} category ModernFlow name Test' ]

**Comment by petrochuk** [comment]
I couldn't repro it. Can you provide steps you followed?

**Comment by GeeksDam** [comment]
Hello 
Just curious 
Any solution to this yet 
Currently facing the same issue on Azure Devops to export a solution package 
 ****Workflow export: FAILURE, workflow id {13f07bb9-8464-ee11-8df0-6045bdcff8f7} category ModernFlow name Create-Input-File****

**Comment by GeeksDam** [comment]
> I couldn't repro it. Can you provide steps you followed?

This is my job flow

**Comment by Rambu24** [comment]
I got the same problem, but my cloud flow uses a custom connector that makes a HTTP Request to API Services. But I tried some suggestions from microsoft, like building the flow inside the solution and putting the custom connector in a separate solution, but it's still not working.
