### ISSUE TITLE
pac admin create-service-principal -env fails v1.25.2

### ISSUE THREAD

**Issue by rajyraman** [microsoft/powerplatform-build-tools#408]
pac version 1.25.2.

![image](https://github.com/microsoft/powerplatform-build-tools/assets/5035266/b4cad63d-4b66-44b5-b106-7385961acf06)

env is a mandatory parameter which was not there in 1.24.3

**Comment by rajyraman** [comment]
@petrochuk - I tried the same in the previous version without the flag and it was able to create the App Registration in Entra Id.

![image](https://github.com/microsoft/powerplatform-build-tools/assets/5035266/2da27000-f011-48b9-b405-1a4dfdfd59ce)

**Comment by rajyraman** [comment]
@petrochuk - WSL2 + dotnet pac tool seems to atleast create the app registration. I get the error below on normal Windows Terminal + pac.

![image](https://github.com/microsoft/powerplatform-build-tools/assets/5035266/7e271b86-e13e-409e-bee4-106637c7fd4d)

**Comment by rajyraman** [comment]
There seems to be a different in behaviour between pac installed using the msi installer and the one installed as dotnet tool. pac as dotnet tool gives error "We didn't find that application ID", while the installer pac gives WINHTTP_CALLBACK_STATUS_REQUEST_ERROR.

**Comment by omnisip** [comment]
This appears to be a race condition caused by not waiting for the azure ad information to propagate.

**Comment by petrochuk** [comment]
Thanks for reporting. We are making changes to add retries and delays in next version

**Comment by rajyraman** [comment]
Seems to be working in the post (https://devblogs.microsoft.com/powerplatform/power-platform-command-line-june-update/), but this still does not work for me in 1.25.5. Is @kanaks using an internal build?

**Comment by rajyraman** [comment]
@petrochuk - Works in dotnet tool pac v1.26.5. Still getting WINHTTP_CALLBACK_STATUS_REQUEST_ERROR in normal msi installed pac. But I am not sure if this is something to do with my machine. Closing the issue.

**Comment by Ralph101** [comment]
Is it also possible to create an App Registration manually? Because when I create a manual SPN WhoAmi works fine but the Copy Environment is broken. @petrochuk

**Comment by petrochuk** [comment]
> Is it also possible to create an App Registration manually? Because when I create a manual SPN WhoAmi works fine but the Copy Environment is broken. @petrochuk

it is absolutely possible. Just go to https://portal.azure.com/ and create App Registration there

**Comment by Ralph101** [comment]
ik looks like the SPN should have the right permissions:

![8v09FMLLH5](https://github.com/microsoft/powerplatform-build-tools/assets/26168480/0a1c0874-5c2a-4cd0-a290-6633c4a2eee5)
