### ISSUE TITLE
PowerPlatformImportSolution fails when solution contains power automate flows - teams environement

### ISSUE THREAD

**Issue by notviva** [microsoft/powerplatform-build-tools#426]
Importing a solution using PowerPlatformImportSolution is giving us this error: 

Error code: 80040217 
Exception message: "Entity 'solution' With Id = fdc8ebe8-6cc4-4e49-a7cc-c5452bb13a25 Does Not Exist" 

When importing this same solution file manually going to the teams environment, this error is not displayed and the import is successful. 

When we remove any power automate flows from this solution, the import with PowerPlatformImportSolution is also successful. 

Therefore we came to the conclusion that something in this flow is using the solutions table and this bug comes up. As we know the solutions entity is a default dataverse table in the environment. So its not really possible that we deleted it and it does exist in the environment. 

The solution is built on a regular dataverse environment and imported in dataverse for teams. 

We can only reproduce the error with teams environment.

**Comment by notviva** [comment]
Attached the log file for import task

[importing_task_logs.txt](https://github.com/microsoft/powerplatform-build-tools/files/12158389/importing_task_logs.txt)

**Comment by petrochuk** [comment]
I looked at log file you attached. I think the error message "Entity 'solution' With Id not found" is masking real issue. I see from log files you have flags "--import-as-holding true --force-overwrite true". When I used these flags, I got import error too:
"Solution manifest import: FAILURE: Cannot create a holding solution for missing base ..." but when I don't import-as-holding it works from Azure DevOps pipeline

**Comment by notviva** [comment]
I think you can't import as a holding solution for the first time. Its only possible with an update. Hence the error.

We chose the holding -> upgrade path because the error message is more informative. 
When importing the solution with `--import-as-holding false` we get this 

`Error: The 'ImportComponent' message is not supported for the Dataverse for Teams offering
    The 'ImportComponent' message is not supported for the Dataverse for Teams offering`

So then after some troubleshooting we got to the solution entity error that we thought is the underlying issue which seems to be a bug.

**Comment by notviva** [comment]
Found the issue. 

Because we tried to use unmanaged solution zip file and use the PowerPlatformImportSolution with parameter `ConvertToManaged: true`
it tried to import it in the default environments solution. 

When we use a managed zip and import that, the build is successful. 

Thanks for your time!
