### ISSUE TITLE
System.ComponentModel.Win32Exception Error when running pac auth create

### ISSUE THREAD

**Issue by SiPurdy** [microsoft/powerplatform-build-tools#472]
I keep on encountering a situation where pac auth create --url <urlOfEnv> results in the following error output:

> Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: fb004ed7-c5de-4173-8acd-8b632a75164a, Exception Type: System.ComponentModel.Win32Exception
> The diagnostic logs can be found at: C:\Users\<USER>\AppData\Local\Microsoft\PowerAppsCLI\Microsoft.PowerApps.CLI.1.25.5\tools\logs\pac-log.txt

I've attached the diagnostic log
[pac error.txt](https://github.com/microsoft/powerplatform-build-tools/files/12343119/pac.error.txt)

Only way to restore correct  functionality is to log out/in or reboot.

I do a lot of auth create/auth clears in any window session, so the "Error creating window handle" might indicate an issue in release of handles??? (I'm no WinForms developer 😄, so that's about as far as I can go.)

**Comment by petrochuk** [comment]
We are using newer version of MSAL library which has some of these issues fixed
