### ISSUE TITLE
Install Build Tools on Azure DevOps Server

### ISSUE THREAD

**Issue by YannickRe** [microsoft/powerplatform-build-tools#478]
We tried installing the Build Tools through Marketplace on an Azure DevOps Server installation, but hit an issue. It just would timeout and not install.
We used some internal cheating tweak to get the vspackage file but that also didn't want to install on the Server. When we tried the 2.0.8 release (the last one posted on GitHub Releases), it had an .vsix and this one DID install for us.

Is Build Tools supposed to work, in it's latest version, on DevOps Server? If yes, what's the approach to take for us?

**Comment by petrochuk** [comment]
@YannickRe
Thanks for letting us know. Attached latest .vsix file: https://github.com/microsoft/powerplatform-build-tools/releases/tag/v2.0.33

**Comment by YannickRe** [comment]
That's lovely, I will report back when I get the client to try it on their DevOps Server 🙂

**Comment by petrochuk** [comment]
on Github Actions @tehcrashxor is separating PAC CLI out to reduce download size:

https://github.com/microsoft/powerplatform-actions/pull/424

**Comment by YannickRe** [comment]
Could be an option too, but in that case wouldn't it be possible to release PAC CLI as a DevOps vsix too and then add a dependency from Build Tools vsix to the PAC CLI vsix?
It would not be a breaking change because DevOps will manage the dependency and make sure you have both extensions installed, and all actions can still run as they should?

Could also be interesting to check if PAC CLI could be installed by default on the Buold Agents: https://github.com/actions/runner-images

**Comment by YannickRe** [comment]
Surprisingly, the client tried it and that new .vsix just works on DevOps Server.
Can I kindly request a monthly release of that .vsix file when you update the Marketplace? 😇
