### ISSUE TITLE
Power Platform Install Tools task failing on Windows x64

### ISSUE THREAD

**Issue by mpil** [microsoft/powerplatform-build-tools#491]
In version 2.0.40 of build tools, the "Power Platform Install Tools" task started failing on self-hosted agents with Windows x64. It was working fine in version 2.0.33. 

We have temporarily switched to Azure Pipelines with ubuntu-latest image which has fixed this. 

Error:

> A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.

**Comment by LMSSonos** [comment]
same issue with the new release. any way to force to install the older version?

**Comment by mpil** [comment]
@LMSSonos I think it automatically installs the newest version for a given organisation and you can't change the version it uses:

![2023-08-22_15h16_34](https://github.com/microsoft/powerplatform-build-tools/assets/11491812/fbb71bc7-6083-4edc-a91e-444131f76d7e)

**Comment by theofilomoraes** [comment]
> @LMSSonos I think it automatically installs the newest version for a given organisation and you can't change the version it uses:
> 
> ![2023-08-22_15h16_34](https://user-images.githubusercontent.com/11491812/262363671-fbb71bc7-6083-4edc-a91e-444131f76d7e.png)

I also think this happens because you can´t set the version, only select the 2.* or 1.*.

**Comment by tehcrashxor** [comment]
v2.0.40 moved from the 2+ year out-of-support Node 10 runner to Node 16, so my guess is that Node 16 isn't installed on your self-hosted agents.

FYI, @anpetroc

**Comment by petrochuk** [comment]
For selfhosted we do have olded VSIX assets of the extension which can be used: https://github.com/microsoft/powerplatform-build-tools/releases

Here are the changes @tehcrashxor is talking about:

https://github.com/microsoft/powerplatform-build-tools/pull/424/files
https://github.com/microsoft/powerplatform-build-tools/pull/436

**Comment by LMSSonos** [comment]
Thanks, I worked around using the old version like this in the pipeline

```         
 - task: PowerPlatformToolInstaller@2.0.33 
    displayName: "Power Platform Tool Installer"
```

**Comment by petrochuk** [comment]
Some background: https://devblogs.microsoft.com/devops/node-runner-update-guidance-for-azure-pipelines-task-authors/

For customers who do not want to run End-of-Life versions of Node, we provide the pipelines-agent-* [release feed](https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/node6.md) that excludes Node 6. By March 2023, this feed will exclude Node 10 as well as Node 6. Customers that install this (self-hosted) agent can only run tasks that use a non-EOL runner (Node 16 today). Any tasks not updated to use Node 16 will fail for agents deployed from this release feed.

***Later in 2023, we will start removing End-of-Life Node runners from our Hosted agents as well*** We will provide a method for customers to still use tasks dependent on the Node End-of-Life runners before we remove those runners from Hosted agents.

**Comment by Robinson308** [comment]
I am seeing the same error on our self-hosted agents. I have upgraded Node.js to v18.17.1 on one agent & restarted. Power Platform Install task is still failing howver - what else do I need to do to fix this?

**Comment by sashi-inss** [comment]
I have done below so far in our self hosted agent and problem still persists, any further suggestion?

- Upgraded the agent to latest
- Updated the operating system
- Installed the Node.JS 16.x inside the agent
- added Node Tool install (16.x) task to the pipeline

**Comment by quaresma-cq** [comment]
Same error here.

##[error]A supported task execution handler was not found. The task does not carry an implementation that is compatible with your current operating system 'Windows(X64)'. Contact the task author for more details.

- Self-Hosted windows agent - Failed
- Azure windows server latest agent - Failed
- Azure ubuntu latest agent - Success

**Comment by petrochuk** [comment]
It is not clear from the log Agent's architecture. I understand the machine is x64 but what about the Azure DevOps agent?

**Comment by petrochuk** [comment]
Just heads up notice that Node 16 is on accelerated deprecation path as well.

https://github.com/microsoft/azure-pipelines-agent/issues/4239

**Comment by quaresma-cq** [comment]
Fixed just updating the agent 

![image](https://github.com/microsoft/powerplatform-build-tools/assets/42184150/69e2c582-defd-46e0-ad3b-fe6ffff48a87)

**Comment by Robinson308** [comment]
Updating the Agent version to 3.225.0 fixed it for me also.
