### ISSUE TITLE
Import solution with the flag SkipLowerVersion set true, where solution isn't present in the environment

### ISSUE THREAD

**Issue by Rhisiart** [microsoft/powerplatform-build-tools#499]
I create a generic task to import a solution to environment.

![image](https://github.com/microsoft/powerplatform-build-tools/assets/36708473/a7a41f91-2a65-4c65-8f1c-be578d439edd)

When importing the new solution. I getting this error  No string called SolutionImportSolutionNotFound found.|EXCEPTION: System.Collections.Generic.KeyNotFoundException: Internal: No string called SolutionImportSolutionNotFound found.

Because is trying to check the version in environment, as the solution is not yet in the environment gives error.

![image](https://github.com/microsoft/powerplatform-build-tools/assets/36708473/29388b31-6604-4130-a101-eb5d3ed4107f)

When the solution is in the environment it works as intended.

![image](https://github.com/microsoft/powerplatform-build-tools/assets/36708473/498cf375-bc1a-4280-bf17-e848392e003a)

My question is should I prevent using the flag when solution isn't present in the environment?

**Comment by strwase** [comment]
In my opinion, if the solution is not present, it should just import, not fail. This should be fixed.

**Comment by petrochuk** [comment]
This is fixed in next version which will be out by end of the month
