### ISSUE TITLE
Copy environment task timeout, auditdata

### ISSUE THREAD

**Issue by scosec** [microsoft/powerplatform-build-tools#515]
Hi,

I'm currently using the copy data environment task. But i'm experiencing some issues with it.

It's not possible to skip audit data through the template. When adding it manually to the command not happens.
I can see it is added to the main branche. We are currently running at v2.0.40, it is not available there. Is there any news on the release cycle?

https://github.com/microsoft/powerplatform-build-tools/blob/main/src/tasks/copy-environment/copy-environment-v2/task.json

Furthermore the job cancels at 60 minutes / 1 hour. Defining the timeoutInMinutes option in the task makes no difference.
I think for larger environments it would be nice to have a longer limit. Especially when the task copies the audit data with it.

![image](https://github.com/microsoft/powerplatform-build-tools/assets/14801619/70e23311-ae66-4196-b077-039f51e22cb3)
![image](https://github.com/microsoft/powerplatform-build-tools/assets/14801619/5d8c79ae-1bdf-4127-9dbf-d33347366c70)

Thanks in advance.

Ivo

**Comment by petrochuk** [comment]
Thanks for your question. We are adding this option in next release which should be out in next few weeks

**Comment by jfurtz** [comment]
We have the same issue with timeout and the possibility skip audit data would be great.
