### ISSUE TITLE
Asynchronous operation failed: an unexpected error occurred

### ISSUE THREAD

**Issue by dspencelink** [microsoft/powerplatform-build-tools#520]
I've had the Power Platform ALM accelerator running for about a month. I ran into a solution yesterday that won't deploy to the next environment. The step that's failing in the pipeline is 'Import Managed Solution as Update'. I've successfully deployed other solutions to this environment last week and today but something seems wrong with the import of this solution. Power Platform Build tool version is 2.40, the latest. Is there a way to get better logging or understand what's failing exactly?  I can manually import the exported solution using the PP admin interface without issue.
This is the error:
===================================================
Asynchronous operation ff43aa63-5c4e-ee11-be6f-002248280d4e failed within 00:00:32.7669229.

The reason given was: An unexpected error occurred.
Microsoft PowerPlatform CLI
Version: 1.26.5+g670cdf9
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: The async operation completed with a statuscode of Failed.
===================================================
![image](https://github.com/microsoft/powerplatform-build-tools/assets/133893716/eb1a767f-d5fb-4ef9-af99-374d0e9df732)

**Comment by petrochuk** [comment]
Try enable diagnostics option to get more detailed logging
![image](https://github.com/microsoft/powerplatform-build-tools/assets/30735471/731f77b2-b16b-4dd1-a4de-9dc37ec9649d)

**Comment by dspencelink** [comment]
Thanks @petrochuk  Enabling system diagnostics helped pinpoint that a connection reference was missing. It's odd, previously if a Solution was missing a reference, it spit out a "MissingDependencies" tag with info about environment variables missing from the solution that were in the power app. I guess I was hoping I'd get the same from missing connection references. I think that was it but I won't know until Monday.

**Comment by dspencelink** [comment]
Rerunning the pipelin and enabling debug mode helped me find the issue.  Thanks.
