### ISSUE TITLE
Reset Environment with service Principle

### ISSUE THREAD

**Issue by h-karthik12** [microsoft/powerplatform-build-tools#531]
### Discussed in https://github.com/microsoft/powerplatform-build-tools/discussions/526

<div type='discussions-op-text'>

<sup>Originally posted by **h-karthik12** September 11, 2023</sup>
I tried to reset the env with service principle and i have added the SP as the system Admin. When i run the
 pac admin reset --environment https://envurl.com
i get this error
Error: The service principal with id '8ce***' for application 3afcf***  does not have permission to access the path 'https://10.0.7.17:20054/providers/Microsoft.BusinessAppPlatform/scopes/admin/environments?`$expand=permissions&api-version=2020-08-01' in tenant 764****.

Not sure what is that i am missing. I can do the same with normal user. Is this feature not available for SP or some privileges needed to be added?</div>

**Comment by snizar007** [comment]
Hello @h-karthik12, Thank you for reporting. Can you share the pac cli log?

**Comment by petrochuk** [comment]
We don't enforce access on build tools side. If user or service principal has access, then operation will be executed or not if identity you are using doesn't have enough privileges.

**Comment by AshV** [comment]
Could you please elaborate which privileges are required exactly and how to assign them? My connections are created using Application user clientid/secret.

**Comment by devkeydet** [comment]
If you have setup your Service Principal / App Registration using `pac admin create-service-principal` the permissions are set for you.  If you created it manually, you need to run an additional command.  There is a PowerShell command called [New-PowerAppManagementApp](https://learn.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/new-powerappmanagementapp) that will give your app registration the necessary permissions to perform Power Platform Admin functions.  I believe `pac application register` is functionally equivalent to [New-PowerAppManagementApp](https://learn.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/new-powerappmanagementapp), but I will let the pac team confirm/clarify whether `pac application register` is functionally equivalent to `New-PowerAppManagementApp`.  If you can't wait for clarification from the pac team, you can review these docs that we have for the ALM Accelerator to do things the "old way".  

@RajeevPentyala - If `pac application register` is functionally equivalent, we should probably update our docs to recommend using the `pac` command over PowerShell.

**Comment by AshV** [comment]
After providing permission using `New-PowerAppManagementApp` I am still getting same error. And `pac application register` is not a valid command. ![image](https://github.com/microsoft/powerplatform-build-tools/assets/7019016/37a44d28-22f9-4ad9-830b-49e55656d17b)

**Comment by AshV** [comment]
![image](https://github.com/microsoft/powerplatform-build-tools/assets/7019016/a86ce40d-84a9-4446-b10f-88c55b3b6abb)

I can see these 4 permissions after executing `New-PowerAppManagementApp` command. What other permissions would be required?
