### ISSUE TITLE
Issue with power platfrom tools with parallal execution on self hosted agents

### ISSUE THREAD

**Issue by PuneethPuni** [microsoft/powerplatform-build-tools#532]
Hi, 

We have configured CI/CD pipelines to import and export crm solutions. for that we use Power Platform Tools. We are using the self-hosted agents running windows server. we run 3 pipelines parallel on the servers. 

We are getting authentication error in 1 out of 3 pipelines and it is random. If we re-run the failed job it is successful. and some jobs failed in between the import also. 

Can someone check this issue. 

'The Authentication Result: \'***\' authenticated successfully.,Validating connection...,Connected to... XXX,Connected as ***,Authentication profile created,    * DATAVERSE    

[ 'Error: No default environment selected for current auth profile. Use auth profile with default environment or pass it as a parameter if command supports it' ]

**Comment by petrochuk** [comment]
We do not support the scenario of running actions in parallel because each actions authenticates and at the end clears authentication profile. I can see how this can randomly interfere with actions running in parallel

**Comment by PuneethPuni** [comment]
@petrochuk Thanks for the clarification.
