### ISSUE TITLE
Process canvas apps not working with latest PowerApps runtime (Authoring version > 3.23084.14)

### ISSUE THREAD

**Issue by gytisa** [microsoft/powerplatform-build-tools#536]
If canvas app authoring version > 3.23084.14 unpack steps fail if "Process CanvasApps" is selected. 
![image](https://github.com/microsoft/powerplatform-build-tools/assets/18726121/175fb786-93d2-4c41-a322-a45fd2259562)
Error messages:
Error   PA3015: Property Removed: AnalysisOptions.DataflowAnalysisEnabled
Error   PA3015: Property Removed: AnalysisOptions.DataflowAnalysisFlagStateToggledByUser

Looks like problem, related to CanvasManifest.json new options inside header element.
> 3.23084.14 header:
{
  "FormatVersion": "0.24",
  "Header": {
    **"AnalysisOptions": {
      "DataflowAnalysisEnabled": false,
      "DataflowAnalysisFlagStateToggledByUser": false
    },**
    "DocVersion": "1.334",
    "MinVersionToLoad": "1.331",
    "MSAppStructureVersion": "2.0"
  },

3.23084.14 header
{
  "FormatVersion": "0.24",
  "Header": {
    "DocVersion": "1.334",
    "MinVersionToLoad": "1.331",
    "MSAppStructureVersion": "2.0"
  },

**Comment by petrochuk** [comment]
we use https://github.com/microsoft/PowerApps-Language-Tooling library like you already linked
