### ISSUE TITLE
Very confusing - How is this different or the same as Power DevOps - 

### ISSUE THREAD

**Issue by devman2k** [microsoft/powerplatform-build-tools#546]

**Comment by petrochuk** [comment]
Tools in this repository are developed by Microsoft with contributions from community.

**Comment by devman2k** [comment]
Yes true.

But the Power Devops Tools is written by a Microsoft employee –

Is this not the same thing?

**Comment by petrochuk** [comment]
Are you referring to [Power DevOps Tools](https://marketplace.visualstudio.com/items?itemName=WaelHamze.xrm-ci-framework-build-tasks)?

**Comment by devman2k** [comment]
Yes exactly - There appears to be 2 sets of tools doing the same thing. Which is Microsoft official and latest?
