### ISSUE TITLE
Bug in harness control on String format for demimal numbers

### ISSUE THREAD

**Issue by pavansarma93** [microsoft/powerplatform-build-tools#548]
Hi Team,

The webpack mentioned [harnesswebpack] (https://learn.microsoft.com/en-us/power-apps/developer/component-framework/debugging-custom-controls#using-developer-tools-with-code-components) is having a FormatterUtils.js as mentioned below is having an invalid method usage.

![image](https://github.com/microsoft/powerplatform-build-tools/assets/49693916/88e926cb-dc6b-46bb-a71d-b2990c1f2c3c)

<img width="309" alt="image" src="https://github.com/microsoft/powerplatform-build-tools/assets/49693916/7d6fd089-0d35-4d54-b28c-8ab9daa75938">

As you can see there is no method or property inside String object to make the return statement. Because of this we are not able to use negative numbers as input/output fields for PCF controls.

However the same is working properly after deployment. I raised this earlier at https://github.com/MicrosoftDocs/powerapps-docs/issues/4688

and was redirected here.

Regards
Pavan

**Comment by petrochuk** [comment]
Closing as this is not related to powerplatform-build-tools repo

**Comment by pavansarma93** [comment]
@petrochuk As you see in description I was redirected here. If this is not the place where should this issue be raised ?
