### ISSUE TITLE
Unable to download power pages site with error 'Error: Unrecognized Guid format.'

### ISSUE THREAD

**Issue by vedg** [microsoft/powerplatform-build-tools#596]
### Discussed in https://github.com/microsoft/powerplatform-build-tools/discussions/582

<div type='discussions-op-text'>

<sup>Originally posted by **ha365** October 10, 2023</sup>
Hi, 
I am getting this error when trying to download my Power Pages site. Is there anyway I can identify where this error is coming from?

Here's the full log

Started downloading website 'site guid'
Connected to... org name
Connected as ha@email.com
Downloading - webfiles
Downloading - powerpagecomponent
Downloading - powerpagesite
Downloading - powerpagesitelanguage
Downloaded - powerpagesite
Downloaded - powerpagecomponent
Downloaded - powerpagesitelanguage
Downloaded - webfiles
Processing - adx_website
Processing - adx_publishingstate
Processing - adx_pagetemplate
Processing - adx_columnpermissionprofile
Processing - adx_webrole
Processing - adx_entitypermission
Processing - adx_cloudflowconsumer
Processing - adx_portallanguage
Processing - adx_websiteaccess
Processing - adx_websitelanguage
Processing - adx_webfile
Processing - adx_sitemarker
Processing - adx_webtemplate
Processing - adx_sitesetting
Processing - adx_webpageaccesscontrolrule
Processing - adx_webpage
Processing - adx_weblinkset
Processing - adx_entityform
Processing - adx_webform
Processing - adx_contentsnippet

WARNING: Expected json value for field adx_attachfilelabel in table adx_entityform ID: 7c87c1b4-6a9a-489b-89c3-b5e469e8d09b

WARNING: Expected json value for field adx_successmessage in table adx_entityform ID: 7c87c1b4-6a9a-489b-89c3-b5e469e8d09b

WARNING: Expected json value for field adx_attachfilelabel in table adx_entityform ID: 7505c196-0c40-ee11-bdf3-0022487fe310

WARNING: Expected json value for field adx_successmessage in table adx_entityform ID: 7505c196-0c40-ee11-bdf3-0022487fe310
Processing - adx_entitylist

WARNING: Expected json value for field adx_searchplaceholdertext in table adx_entitylist ID: 8bea662f-1c73-4362-b4ef-62bbb23ac76b

WARNING: Expected json value for field adx_searchplaceholdertext in table adx_entitylist ID: bbff093d-bf43-479d-b5f3-107012238a34
Processing - annotation
Processing - adx_weblink
Processing - adx_entityformmetadata
Processing - adx_webformstep
Processing - adx_webformmetadata
Updating manifest...
Microsoft PowerPlatform CLI
Version: 1.27.6+g9f62afb
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: Unrecognized Guid format.
</div>

**Comment by allandecastro** [comment]
@vedg : Do you have a screen or something about the error ?

**Comment by ha365** [comment]
> @vedg : Do you have a screen or something about the error ?

Hello Allan, here's a screenshot of the original error. Same as the log above. We want to update our site to the latest bootstrap version but our still stuck with this issue.

![image](https://github.com/microsoft/powerplatform-build-tools/assets/47410306/0892093e-b6e9-4dfc-b5ba-55f1a28ee8b4)

**Comment by JoshChun** [comment]
We've circumvented this issue by excluding the adx_webformstep entity from download. Culprit seems to be related to setting up advanced forms.

**Comment by ha365** [comment]
@JoshChun Thanks. I will try to find the culprit on my side.
Did you find anything on your adx_webformstep entity which relates to this error message? Anything that you may think is the culprit?

**Comment by ha365** [comment]
Hello,
Our issue was resolved after working with MS consultant today. The issue was caused by the data corruption of Table permissions. We created some roles and assigned them to a table permission. Later on, the roles were deleted so there was a missing reference on the table permission. 

Here you can see blank IDs on the webroles. For a quick test I deleted this permission and was able to download the site.

adx_accountrelationship: 
adx_append: true
adx_appendto: true
adx_childTablePermissions: []
adx_contactrelationship: 
adx_create: true
adx_delete: true
adx_entitylogicalname: salesorderdetail
adx_entityname: All sales order lines
adx_entitypermission_webrole:
- ''
- ''
- 9cf53d8c-80f8-ed11-8849-6045bx8c55f1
- e8e62e87-80f8-ed11-8849-6045bd8cz384
adx_entitypermissionid: 125115bd-0bfe-ed11-8f6e-6045bd8c55zx
adx_parententitypermission: 
adx_parentrelationship:

**Comment by MrRishabhJain** [comment]
We have made enhancements in this area in pac 1.32.x.
