### ISSUE TITLE
Issue downloading Power Pages with enhanced data model

### ISSUE THREAD

**Issue by BernardThorpe** [microsoft/powerplatform-build-tools#611]
PAC CLI Versions Issue Replicated With: 1.28.2, 1.28.3
Command: pac powerpages download -p ./Portal -id {guid} --modelVersion 2

CLI Error:
Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: {guid}, Exception Type: System.AggregateException

Log Error:
Exception details: 
ErrorCode: 0x80090017
Message: Downloading in multiple chunks is not supported for the files stored in the database.
TimeStamp: 2023-11-01T22:17:24.7988278Z

**Comment by petrochuk** [comment]
The issue is resolved. If you see the problem again feel free to reopen.
