### ISSUE TITLE
Timeouts when deleting large solutions

### ISSUE THREAD

**Issue by markus-codechefs** [microsoft/powerplatform-build-tools#641]
After solving Issue #328, when deleting large solutions we now get a new timeout error at 4min 47 sec as follows:

```
Error: An error occurred while receiving the HTTP response to https://xxxxxx.crm4.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.49.4384. This could be due to the service endpoint binding not using the HTTP protocol. This could also be due to an HTTP request context being aborted by the server (possibly due to the service shutting down). See server logs for more details.
    The underlying connection was closed: An unexpected error occurred on a receive.
        Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
            An existing connection was forcibly closed by the remote host
```
Is there an httpclient where we might be able to configure a higher timeout? 

We are using "microsoft-IsvExpTools.PowerPlatform-BuildTools.delete-solution.PowerPlatformDeleteSolution@2" and we are on the latest version 2.0.47.

**Comment by venkatakarthik91** [comment]
We are also facing the same issue while deleting solution using Azure Pipelines. The solution is getting deleted but the step is failing in the pipeline. Error message and screenshot is given below.


_Error: An error occurred while receiving the HTTP response to https://***.crm16.dynamics.com/XRMServices/2011/Organization.svc/web?SDKClientVersion=9.2.49.3165. This could be due to the service endpoint binding not using the HTTP protocol. This could also be due to an HTTP request context being aborted by the server (possibly due to the service shutting down). See server logs for more details.
The underlying connection was closed: An unexpected error occurred on a receive. Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. An existing connection was forcibly closed by the remote host._

![image](https://github.com/microsoft/powerplatform-build-tools/assets/13254539/e38dc3f2-09ed-4efd-8794-9b9a09950f04)

**Comment by parvezghumra** [comment]
We are seeing a similar error trying to delete a solution using the Power Platform Github Action (Delete Solution). We can see in the Solution History in the target environment that the actual deletion of the solution succeeds in 13 mins, but the corresponding step in the Github Action workflow times out after 30 mins. Here's the log

@snizar007 @petrochuk Any updates on this?

```
loading action yaml file: D:\a\_actions\microsoft\powerplatform-actions\v1\delete-solution\action.yml
  authN to env. authType:UserPass authScheme:; cloudInstance: Public; envUrl: https://xxxx.crm4.dynamics.com/
  '***' authenticated successfully.
  Validating connection...
  Connected to... xxx
  Default organization: xxx
  Authentication profile created
      * UNIVERSAL                                : ***                    Public https://xxx.crm4.dynamics.com/   
  
  Microsoft PowerPlatform CLI
  Version: 1.30.6+g613576f
  Online documentation: https://aka.ms/PowerPlatformCLI
  Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions
  
  Warning: Argument --url will be deprecated soon. Please use --environment instead.
  
  The Authentication Result: '***' authenticated successfully.,Validating connection...,Connected to... xxx,Default organization: xxx,Authentication profile created,    * UNIVERSAL                                : ***                    Public https://xxx.crm4.dynamics.com/   ,,Microsoft PowerPlatform CLI,Version: 1.30.6+g613576f,Online documentation: https://aka.ms/PowerPlatformCLI,Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions,,Warning: Argument --url will be deprecated soon. Please use --environment instead.,
  Calling pac cli inputs: solution delete --solution-name xxxx
  Connected as ***
  Connected to... xxx
  
  Deleting Dataverse Solution...
  Microsoft PowerPlatform CLI
  Version: 1.30.6+g613576f
  Online documentation: https://aka.ms/PowerPlatformCLI
  Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions
  
  Error: The request channel timed out while waiting for a reply after 00:30:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
      The HTTP request to 'https://xxx.crm4.dynamics.com/XRMServices/[20](https://github.com/xxx/xxx/actions/runs/8045928388/job/21972155844#step:18:21)11/Organization.svc/web?SDKClientVersion=9.2.49.6443' has exceeded the allotted timeout of 00:[30](https://github.com/xxx/xx/actions/runs/8045928388/job/21972155844#step:18:31):00. The time allotted to this operation may have been a portion of a longer timeout.
          The operation has timed out
```

**Comment by snizar007** [comment]
Hello All, upon investigating, this does not seem to be in PAC CLI area, and it is suggested that PAC CLI, which is the underneath layer of ADO PPBT, GitHub Actions for PP, is expecting a service finished response and is not getting despite already being finished. There isn't much can be done from PAC CLI side at the moment.

**Comment by parvezghumra** [comment]
Thanks @snizar007. Please could you suggest what alternative channels this could be progress via please?

**Comment by markus-codechefs** [comment]
Since this is the wrong area for the issue I will close it thanks for the info @snizar007
