### ISSUE TITLE
pac pcf push - cannot upload the component

### ISSUE THREAD

**Issue by brasov2de** [microsoft/powerplatform-build-tools#652]
With the latest version of "pac cli" , "pac pcf push" cannot import the pcf anymore. 
My PCF was already uploaded with older "pac cli" version, and I think the error happens only if the PCF was already uploaded.

I've noticed that inside the "obj" folder, it generates a folder "PowerAppsToolsTemp_" (and cdsproj). 
With an older "pac cli" version, the folder is called "PowerAppsTools_" and the "pac pcf push" works.

Latest version where it works for me "Version: 1.28.3"
The latest versions: VSCode extension "Version: 1.28.3" or the standalone "Version: 1.29.6" doesn't work.

Error Message
"2023-11-27 15:29:23.4043 | ERR | Microsoft.PowerPlatform.Dataverse.Client.ServiceClient :: ************ FaultException`1 - Delete : Delete Request to Dataverse via IOrganizationService |=> The object you tried to delete is associated with another object and cannot be deleted. Deleting records from Publisher (ObjectTypeCode: 7101)
for Id(s) : 2fd65450-2887-4b5d-8b90-14820074774a
Exception : Cascade Delete failed due to cascade restrict relation. Details below :
Restricting entity Solution (ObjectTypeCode: 7100) has Id: adc713e9-6684-437f-a4b6-4411c50466fd and is collected by Relationship with name: publisher_solution.

Source: mscorlib
Method: HandleReturnMessage
DateUTC: 11/27/2023
TimeUTC: 3:29:23 PM
Error: Message: The object you tried to delete is associated with another object and cannot be deleted. Deleting records from Publisher (ObjectTypeCode: 7101)
for Id(s) : 2fd65450-2887-4b5d-8b90-14820074774a
Exception : Cascade Delete failed due to cascade restrict relation. Details below :
Restricting entity Solution (ObjectTypeCode: 7100) has Id: adc713e9-6684-437f-a4b6-4411c50466fd and is collected by Relationship with name: publisher_solution.
"

**Comment by trindadeti** [comment]
Same issue here guys.
Downgraded to v1.1.28 and worked for me.
Thanks for posting!

**Comment by joem-msft** [comment]
Link to other issue: https://github.com/microsoft/powerplatform-vscode/issues/780

This issue is fixed with Pac CLI v1.30.6, but the release to the VS Code extension is in progress; should be released in the next couple days.

**Comment by brasov2de** [comment]
I've just tested it with the pac cli v1.30.6 and it works now. Even the option --solution-unique-name (insted of -pp) worked.
Thanks a lot for fixing the issue!

**Comment by joem-msft** [comment]
The Power Platform Extension for VS Code v2.0.28 has been released and contains the fixes above.
