### ISSUE TITLE
GCC - Unable to assign security role using pac command

### ISSUE THREAD

**Issue by sanjeev40084** [microsoft/powerplatform-build-tools#658]
I am trying to assign security role to one of the user but it keeps erroring out with 'Access token validation failure. Invalid audience.' error message. The auth profile that i used does have **SA role** and i am in **GCC instance**. I am in version **1.29.11**

`pac admin assign-user -env 'env-id' 'u 'user@gmail.com' -r 'System Administrator'`

![image](https://github.com/microsoft/powerplatform-build-tools/assets/3292092/abddd4c9-a954-45ca-9815-f5b987277123)

**Comment by tehcrashxor** [comment]
Looks like the Graph endpoints were misconfigured - GCC Moderate orgs (crm9) were mapped to use the GCC High / L4 endpoint, and GCC High orgs were not mapped at all.

Tracking internally with [AB#26729692](https://msazure.visualstudio.com/OneAgile/_workitems/edit/26729692)

**Comment by tehcrashxor** [comment]
Endpoint mapping should be fixed via [PAC v1.30.7](https://www.nuget.org/packages/Microsoft.PowerApps.CLI/1.30.7)
