### ISSUE TITLE
PAC CLI Unpack and Pack managed solution organization setting missing

### ISSUE THREAD

**Issue by h-karthik12** [microsoft/powerplatform-build-tools#695]
I am trying to pack the managed solution using PAC CLI for our automated pipeline. I am seeing some peculiar behavior

when we use unpack command it unpacks all the components

```pac solution unpack -z solution.zip -f CustomCode  -p managed -loc -lcid```

This is the folder after extract
![image](https://i.stack.imgur.com/jxCnW.png)

but when we pack the same soultion again the organization setting folder will be removed

```pac solution pack -z solution.zip -f CustomCode  -p managed -loc -lcid``` 

![image](https://i.stack.imgur.com/in8YC.png)
Not sure why this behaviour in the pac cli

**Comment by sergeytunnik** [comment]
Seems related to my ticket for vscode power platform repo: https://github.com/microsoft/powerplatform-vscode/issues/797

**Comment by h-karthik12** [comment]
> Seems related to my ticket for vscode power platform repo: [microsoft/powerplatform-vscode#797](https://github.com/microsoft/powerplatform-vscode/issues/797)

Yes correct

**Comment by iggsn** [comment]
Same here. Unpack works and creates the organisationsettings-folder and files. Pack ist just ignoring the organizationsettings-folder.
Any idea, if and when this can be fixed?

**Comment by tehcrashxor** [comment]
Fixed with last week's PAC v1.31.6 release.
