### ISSUE TITLE
Large solution upgrade failing during the upgrade stage

### ISSUE THREAD

**Issue by sivak795** [microsoft/powerplatform-build-tools#696]
Context:
We are running an Azure devops pipeline to deploy the solutions to the Target PP environments.
During the upgrade process is failing.  Here is the excerpt of the log.

[Logfile for failure.txt](https://github.com/microsoft/powerplatform-build-tools/files/13836097/Logfile.for.failure.txt)

![image](https://github.com/microsoft/powerplatform-build-tools/assets/128185358/6ac3821e-a587-4cd5-8bf5-dda690dad310)

**Comment by sivak795** [comment]
I have changed the connection urls for the privacy purpose

**Comment by craig-lund-palm** [comment]
I gave this a test with my test solution in GCC. I was able to get solutions to upgrade using both methods. 

        - Upgrade Immediately - No errors. 
        - Stage and upgrade - No errors.

There were some backend updates yesterday across GCC that may have contributed to some erroneous errors as well.

I do understand that the issue was able to be resolved. Would be great to hear the details of your experience.

**Comment by sivak795** [comment]
Thanks, Craig, for checking. Things are working fine now. I also suspect some of the updates could have caused some issues too. I agree to your point.

**Comment by sivak795** [comment]
> I gave this a test with my test solution in GCC. I was able to get solutions to upgrade using both methods.
> 
> ```
>     - Upgrade Immediately - No errors. 
>     - Stage and upgrade - No errors.
> ```
> 
> There were some backend updates yesterday across GCC that may have contributed to some erroneous errors as well.
> 
> I do understand that the issue was able to be resolved. Would be great to hear the details of your experience.

Thanks, Craig, for checking. Things are working fine now. I also suspect some of the updates could have caused some issues too. I agree to your point.

**Comment by tehcrashxor** [comment]
From the above, looks like a transient issue outside of the ADO Tasks.   As it looks both external and already resolved, closing this Issue.  Feel free to reopen if it reoccurs.
