### ISSUE TITLE
Invalid option listed in authentication

### ISSUE THREAD

**Issue by js9331** [microsoft/powerplatform-build-tools#727]
https://github.com/microsoft/powerplatform-build-tools/blob/66a8161e316ea5e2f9a2a332a0bdb12c5129f7c4/src/tasks/checker/checker-v2/task.json#L40C1-L40C74

The options at the referenced line include the auth option for username/password, but this task only supports service principal auth. 

This limitation is mentioned in https://learn.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks#yaml-snippet-checker, but this task.json includes the invalid option.

**Comment by tehcrashxor** [comment]
Username/Password is a valid option.  The docs are very out of date.

FYI @marcelbf and @JimDaly - looks like the PPBT docs reference the 2+ year out of date v0 tasks for _most_ of the tasks.

**Comment by JimDaly** [comment]
@phecke is your contact for the ALM docs.

**Comment by marcelbf** [comment]
@snizar007 can you please work with Peter to update this

**Comment by phecke** [comment]
@js9331 Thanks for pointing this issue out. The article has been updated.
