### ISSUE TITLE
Error: You're trying to use an expired authentication profile. Please either switch to different profile or delete and recreate the profile again.

### ISSUE THREAD

**Issue by dylanhaskins** [microsoft/powerplatform-build-tools#731]
Switched pac to use the --environment flag for the universal profile. Works the first time, then it appears after the auth token expires, nothing works anymore. Whether I try a list, create, delete, select etc. I always get an expired authentication profile error, so it becomes impossible to recreate a new profile or remove an existing one :(

pac auth list
Microsoft PowerPlatform CLI
Version: 1.30.4+gc285477
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: You're trying to use an expired authentication profile. Please either switch to different profile or delete and recreate the profile again.

**Comment by petrochuk** [comment]
Thank you for reporting. We are aware of the issue and working on the fix which we hope to push out soon

**Comment by tehcrashxor** [comment]
Fixed with the release of PAC v1.30.5
