### ISSUE TITLE
pac powerpages download not working correctly

### ISSUE THREAD

**Issue by positiveDimension** [microsoft/powerplatform-build-tools#733]
Hello,
We have upgraded our portal from standard to enhanced. However, when we attempt to download the portal in Visual Studio Code, we encounter an error.

The error message we receive is:

Updating manifest...
Microsoft PowerPlatform CLI
Version: 1.29.11+g9e2b163
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions
Error: Input string was not in a correct format.

After attempting to downgrade the CLI to versions 1.28.3 and 1.24.3, we still face the same error.

We've checked the log file located at C:\Users%username%\AppData\Roaming\Code\User\globalStorage\microsoft-isvexptools.powerplatform-vscode\pac\tools\logs, but we couldn't find any exceptions or errors recorded.

Any advice would be greatly appreciated.

**Comment by dynam0r** [comment]
Hi, bumping this! Did you find a reason and a fix for this behaviour? I'm encountering similar problem.

**Comment by positiveDimension** [comment]
> Hi, bumping this! Did you find a reason and a fix for this behaviour? I'm encountering similar problem.

Unfortunately, no. I have tried downgrading version of Power Apps CLI to 1.28.3 and 1.29.*  I have also been in contact with MS support regarding this, but they couldn't find what is causing this issue.

**Comment by Glideh** [comment]
I have this too with the version 1.30.7.
The site seems to get downloaded but it's always outputting this error at the end since a couple of weeks.

> Error: Input string was not in a correct format.

**Comment by marlierdamien** [comment]
@positiveDimension Did you find anything since ?

**Comment by MrRishabhJain** [comment]
Hey @marlierdamien, @positiveDimension, @Glideh, @dynam0r, can you try upgrading to PAC v1.32.8 as it has enhancements that should throw more light on this issue.
