### ISSUE TITLE
PowerPlatformDeployPackage task error: The value passed to '--url' is invalid

### ISSUE THREAD

**Issue by khoait** [microsoft/powerplatform-build-tools#756]
Hi,

I'm using Power Platform Build Tools 2.0.52, the Power Platform CLI the build tool is using is 1.30.7+ge6211cf.

In my Azure YML pipeline, I'm using the PowerPlatformDeployPackage@2 step as below

```yml
- task: PowerPlatformDeployPackage@2
  inputs:
    authenticationType: "PowerPlatformSPN"
    PowerPlatformSPN: "Test Connection"
    PackageFile: "$(Pipeline.Workspace)/solutionpackage/DeploymentPackage.dll"
    logConsole: true
```

and I got this error:

```
Microsoft PowerPlatform CLI
Version: 1.30.7+ge6211cf
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: The value passed to '--url' is invalid. No Dataverse organization was found matching the specified criteria (--url https://***test.crm4.dynamics.com/).

Warning: Argument --url will be deprecated soon. Please use --environment instead.

[ 'Authentication profiles and token cache removed' ]
[
  'The Clear Authentication Result: Authentication profiles and token cache removed'
]
##[error]Error: '***' authenticated successfully.
Microsoft PowerPlatform CLI
Version: 1.30.7+ge6211cf
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: The value passed to '--url' is invalid. No Dataverse organization was found matching the specified criteria (--url https://***test.crm4.dynamics.com/).

Warning: Argument --url will be deprecated soon. Please use --environment instead.
```

I think this is because the CLI is updated to a new version but the task is not updated to pass the correct argument to the `pac package deploy` command

**Comment by dadokps** [comment]
Hello, i am also facing this Problem. Any Suggestion/Solution for this?

**Comment by duuuy7** [comment]
Hey I had the same error. 

I solved it by adding the AppUser (Service Connection) to the environment Crm Environment

aka.ms/ppac > Environment > Select your environment > Users > App users list > Add new app user

**Comment by khoait** [comment]
@duuuy7 thanks! that fixes the error. I'm not sure how I could have missed that step. But the Error and Warning in the build task is bit missing leading I think. I'll close this issue then.

**Comment by dadokps** [comment]
> Hey I had the same error.
> 
> I solved it by adding the AppUser (Service Connection) to the Crm Environment
> 
> aka.ms/ppac > Environment > Select your environment > Users > App users list > Add new app user > Select your app user and grant them a security role (I granted them the systemadministrator role)

Thanks.

**Comment by Hjaf** [comment]
I have this error even though the user is listed in the environment with the system administrator role.

**Comment by dijkmhr** [comment]
I have see this error even though the user is listed in the environment with teh sysem administrator role. Is there another solution?
