### ISSUE TITLE
PAC CLI doesn't throw any errors or return a non 0 error code when an error occurs

### ISSUE THREAD

**Issue by mVermaat** [microsoft/powerplatform-build-tools#785]
I'm trying to call PAC CLI commands in a PowerShell script. When an error occurs, the CLI still returns errorcode 0. Is there any way to detect that something went wrong when you run a PAC CLI command?

**Comment by petrochuk** [comment]
Make sure you are calling pac.exe and not pac.cmd

**Comment by mVermaat** [comment]
That works, thanks.
