### ISSUE TITLE
Auth profile switches during export solution

### ISSUE THREAD

**Issue by strwase** [microsoft/powerplatform-build-tools#788]
We have multiple customers in our Azure DevOps environment, with different Projects and service references.

However, now and then, when running a pipeline that does an export solution. we see the auth profile switch mid-run.

for example 

![image](https://github.com/microsoft/powerplatform-build-tools/assets/10077785/380781f9-4392-4bc7-82b8-105cd6898edc)

This of course causes the export to fail, because the solution defined in the pipeline does not exist in the environment the auth profile switches to.

This is a huge issue, because we're the solution names to match, It would export data from an entirely different customer and import it to another one

**Comment by tehcrashxor** [comment]
Is your pipeline running on self-hosted agents?

The only time we've seen this symptom before is when users are running multiple agents on a single machine/VM.  PAC (which the Power Platform Build Tools) runs under the covers can only have a single active profile, so a second pipeline on the same machine may have logged in to the other profile between this task's login and export steps.

Note that the [self-hosted agents documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=yaml%2Cbrowser#self-hosted-agents) explicitly mentions:
![image](https://github.com/microsoft/powerplatform-build-tools/assets/3751389/ca271c3d-5b44-4411-883a-6e0457cb4223)

**Comment by strwase** [comment]
It is indeed running on a self hosted environment.
Thanks for the clarification, I'll change our internal config to accommodate this problem
