### ISSUE TITLE
PAC CLI command not including .yaml files in packaged solution

### ISSUE THREAD

**Issue by DanK1234567** [microsoft/powerplatform-build-tools#814]
In our DevOps pipeline, the solution zip file is packed from git repository.  I have a custom PowerFx function on a field and the output folder in Git contains the .yaml file, but not the packaged zip file.
![Power DevOps tools Installer](https://github.com/microsoft/powerplatform-build-tools/assets/166534218/1058ae0c-bed4-45c8-a80a-a7239e498458)
![2 - Repository](https://github.com/microsoft/powerplatform-build-tools/assets/166534218/b30c5f9a-b88b-48e9-8462-e284cb95b18b)
![3 - Download with filter](https://github.com/microsoft/powerplatform-build-tools/assets/166534218/26fa10a2-0da8-4f86-9b36-aa612d590cff)
![4 - Download without Filter](https://github.com/microsoft/powerplatform-build-tools/assets/166534218/5fe631e9-e731-4ba5-8920-e1c43e65549e)

**Comment by tehcrashxor** [comment]
The screenshot shows that you're using a Wael Hamze's [Power DevOps Tools](https://marketplace.visualstudio.com/items?itemName=WaelHamze.xrm-ci-framework-build-tasks).  This is not our [Power Platform Build Tools](https://marketplace.visualstudio.com/items?itemName=microsoft-IsvExpTools.PowerPlatform-BuildTools), but a third party extension not supported by our team. 

You may want to open an issue at https://github.com/WaelHamze/dyn365-ce-vsts-tasks/issues
