### ISSUE TITLE
[Feature] The ability to create Developer environments

### ISSUE THREAD

**Issue by ramontebar** [microsoft/powerplatform-build-tools#849]
Currently it is not possible to create a Developer environment using Power Platform Build Tools (2.0.63):

![image](https://github.com/microsoft/powerplatform-build-tools/assets/7858467/080eaab3-646a-4b3a-bd78-47b6434e7a9c)

However, [Power Platform CLI](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/admin#pac-admin-create) already provides this feature by using the parameter **[ --user](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/admin#--user--u-1)**. Example:

```
pac admin create `
--name "RamonTebar DEV Environment" `
--type 'Developer' `
--domain 'ramontebar-dev' `
--currency 'USD' `
--language 'English' `
--region 'unitedstates' `
--async false `
--user '93bc9055-mef5-47ad-bjfe-1a30aef906zx'
```
Could it be possible to integrate this feature please?

**Comment by devkeydet** [comment]
PR: https://github.com/microsoft/powerplatform-build-tools/pull/850
