### ISSUE TITLE
Power Platform Chatbot Copilot Studio: Issue with publishing Copilots

### ISSUE THREAD

**Issue by Aditi3981** [microsoft/powerplatform-build-tools#867]
All of our copilots are taking forever to publish the chatbot. It keeps on spinning saying it is Publishing as following. Is there a way to stop or reset it?
![image](https://github.com/microsoft/powerplatform-build-tools/assets/60483804/d95cee74-77c4-4397-b078-3b8d31ff3fba)

**Comment by petrochuk** [comment]
Can you clarify how this is related to [Microsoft Power Platform Build Tools for Azure DevOps](https://learn.microsoft.com/en-us/power-platform/alm/devops-build-tools) or should we forward this issue somewhere else?

**Comment by Aditi3981** [comment]
We have opened it in Copilot channel. I will close it for now. Thank you.

**Comment by Aditi3981** [comment]
We have opened it in Copilot channel. I will close it for now. Thank you.
