### ISSUE TITLE
version 2.0.69 causes pac paportal upload failure

### ISSUE THREAD

**Issue by mphhohku** [microsoft/powerplatform-build-tools#885]
> 'Sorry, the app encountered a non recoverable error and will need to terminate. The exception details have been captured and will be forwarded to the development team, if telemetry has been enabled. Exception Id: <id>, Exception Type: System.InvalidCastException'

I was using 2.0.63 a while ago, but when using 2.0.69 starting today because I am using Azure DevOps pipelines, this would cause the above error.

**Comment by majakubowski** [comment]
I found the same issue - log attached to the comment.
We are using model V1 for Power Pages. Build Tools with version 2.0.63 works correctly. The issue occurs also in Power Apps CLI versions: 1.32.5, 1.32.6. pac version 1.31.6 works correctly. 

[pac-log.txt](https://github.com/microsoft/powerplatform-build-tools/files/15339787/pac-log.txt)

**Comment by MrRishabhJain** [comment]
PAC v1.32.7 published with the fix. @mphhohku / @majakubowski, can you please update to this version and try again?

**Comment by majakubowski** [comment]
@MrRishabhJain both pac 1.32.7 and ADO Build Tools 2.0.70 works fine :) Thank you for really quick bugfix!
