### ISSUE TITLE
The 'pac solution unpack' command is failing when the '-pca' parameter is passed

### ISSUE THREAD

**Issue by RajeevPentyala** [microsoft/powerplatform-build-tools#914]
Encountering the following issue while triggering the command: pac solution unpack -z "D:\solution.zip" -f "D:\solcloneissue" -pca

_Processing Component: CanvasApps
 - lx_usecasemanagementapp_22fee

-- unpacking Canvas app lx_usecasemanagementapp_22fee...
Unpack from D:\solcloneissue\CanvasApps\lx_usecasemanagementapp_22fee_DocumentUri.msapp --> D:\solcloneissue\CanvasApps\src\lx_usecasemanagementapp_22fee
  source format version: 0.24
Warning PA2001: Checksum mismatch. Checksum indicates that sources have been edited since they were unpacked. If this was intentional, ignore this warning.
Microsoft PowerPlatform CLI
Version: 1.32.8+gf89d946
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: Error   PA3013: Property Value Changed: UsedTemplates[0].Name
Error   PA3013: Property Value Changed: UsedTemplates[0].Template
Error   PA3013: Property Value Changed: UsedTemplates[0].Version
Error   PA3013: Property Value Changed: UsedTemplates[1].Name
Error   PA3013: Property Value Changed: UsedTemplates[1].Template
Error   PA3013: Property Value Changed: UsedTemplates[1].Version
Error   PA3013: Property Value Changed: UsedTemplates[2].Name
Error   PA3013: Property Value Changed: UsedTemplates[2].Template
Error   PA3013: Property Value Changed: UsedTemplates[2].Version
Error   PA3013: Property Value Changed: UsedTemplates[3].Name
Error   PA3013: Property Value Changed: UsedTemplates[3].Template
Error   PA3013: Property Value Changed: UsedTemplates[3].Version
Error   PA3013: Property Value Changed: UsedTemplates[4].Name
Error   PA3013: Property Value Changed: UsedTemplates[4].Template_

**Comment by mgadsden** [comment]
I have the same issue with the 2.0.71 version

**Comment by Masciuniria** [comment]
Temporarily solved with this **magic amazing trick** 🧙:
[Solved: Commit to GIT error since today - Page 2 - Power Platform Community (microsoft.com)](https://powerusers.microsoft.com/t5/Building-Power-Apps/Commit-to-GIT-error-since-today/td-p/2792452/page/2?lightbox-message-images-2794045=878423iAC3D0E6057F4B968)

**Comment by Masciuniria** [comment]
@marcelbf was it fixed? in which release version can I find it?
