### ISSUE TITLE
pac soution unpack failing

### ISSUE THREAD

**Issue by rfarris2000** [microsoft/powerplatform-build-tools#915]
Unpacking a solution with studio version 3.24054.19 causes the following error to be thrown:

PA3999: Unable to parse template file PowerApps_CoreControls_ComboboxCanvasTemplate_dataField

Rolling back to version 3.24052.30 and recommitting fixes the issue temporarily.  If a change needs to be made however, the version gets updated back to 3.24054.19.

**Comment by chrispiasecki** [comment]
Same issue here.

**Comment by marcelbf** [comment]
I believe this issue is related to this fix:
https://github.com/microsoft/PowerApps-Tooling/pull/670

Update pac cli to the latest version to get this fix.

if still able to reproduce the issue, please, open a new one in https://github.com/microsoft/PowerApps-Tooling repo
