### ISSUE TITLE
Getting error about misconfigured federated credentials in task using WIF

### ISSUE THREAD

**Issue by jcksonhe** [microsoft/powerplatform-build-tools#916]
Hi team,

In need of some help setting up a release pipeline using the `Power Platform Import Solution` task using WIF

I've followed the instructions here: https://github.com/microsoft/powerplatform-build-tools/discussions/884
But just in case I missed a step, I'll sum up what I've done:
1. Created an app registration, noting the app & tenant IDs
2. Created a Power Platform service connection using WIF, using the noted app ID for the service principal ID (and tenant ID for the tenant ID):
3. On the app registration, add federated credentials following the discussion above:
    - Issuer: `https://vstoken.dev.azure.com/{OrgId}`
    - Subject Identifier: `sc://{OrgName}/{ProjectName}/{ServiceConnectionName}`

However, in my release pipeline using the "Power Platform Import Solution" task pointing to this service connection, I get the following error:
![image](https://github.com/microsoft/powerplatform-build-tools/assets/8689181/73ea2c55-804a-4a80-b960-d5ace663e570)

I've quadruple-checked the Issuer and Subject Identifier - They are definitely correct. Did I miss a step or configure something else incorrectly? Any help would be greatly appreciated.

Thanks!

**Comment by devkeydet** [comment]
Nothing obvious jumps out at me.  Have you reviewed this discussion?
https://github.com/microsoft/powerplatform-build-tools/discussions/884

**Comment by petrochuk** [comment]
For Managed Identity `pac cli` essentially uses [DefaultAzureCredential](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#defaultazurecredential) which goes through 8 step process to discover identity we can use.

**Comment by jcksonhe** [comment]
> For Managed Identity `pac cli` essentially uses [DefaultAzureCredential](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#defaultazurecredential) which goes through 8 step process to discover identity we can use.

Thanks! Will try this.

**Comment by tehcrashxor** [comment]
Hmm.
@jksonhe, while the red error explains what those values should be, there should also be error text (probably not highlighted in red) in the output below the line in your screenshot.

As an example, one our test pipelines with intentionally misconfigured federation
![image](https://github.com/microsoft/powerplatform-build-tools/assets/3751389/83f3edbc-3ba3-4ead-bafd-f56b1031bd85)
has the full error message coming from AAD / Entra ID.

What does that text say?

-------------------------

The fact that the issuer text in the error you shared is being replaced by the `[***]` log redaction makes that annoying to double check if you have the correct value.   Note that the OrgID value there is not your CRM/PowerPlatform Org ID, but the Azure DevOps OrdID your pipeline is in.  Could the perhaps be the issue?

**Comment by jcksonhe** [comment]
@tehcrashxor Thanks for looking at this. I got the OrgId using this GET call, replacing `OrgName` with the same name in ADO:
https://dev.azure.com/_apis/resourceAreas/79134C72-4A58-4B42-976C-04E7115F32BF?accountName={OrgName}&api-version=5.0-preview.1

As for the error, I have the exact message as you
![image](https://github.com/microsoft/powerplatform-build-tools/assets/8689181/838f9735-ca1a-401e-a74e-171157ee7958)

**Comment by tehcrashxor** [comment]
@jcksonhe, unfortunately the important bit of that line requires scrolling further to the right.
`AADSTS700211` appears to be the error code for having a wrong value for the issuer.
(`AADSTS700213` - error for wrong subject, `AADSTS70025` - error for no federated credentials on the SPN)

**Comment by tehcrashxor** [comment]
Making that API call for our test org returns a different GUID than that test org's Org ID.

Since the value is being redacted in the logs, you should also be able to find that value from making a Service Connection for Azure Resource Manager.  Example:

Create a new service connection, selecting `Azure Resource Manager`
![image](https://github.com/microsoft/powerplatform-build-tools/assets/3751389/58b89f4e-5449-4726-bd32-871a9e55a9f7)

Choose `Workload Identity Federation (manual)`, and hit "Next"
![image](https://github.com/microsoft/powerplatform-build-tools/assets/3751389/d17cd022-1043-47dd-8402-ef43c3c467c4)

Fill out any name and click "Next"
![image](https://github.com/microsoft/powerplatform-build-tools/assets/3751389/b4823864-e8eb-450c-ad20-404a6ec494b1)

Copy the Issuer field provided on that next page:
![image](https://github.com/microsoft/powerplatform-build-tools/assets/3751389/accc5ea8-3cd0-40ba-966d-8b127244ab33)

Then feel free to delete the draft ARM service connection.

We would like to make our own Service Connection behave like the Azure Resource Manager one does, providing those details at creation time.  Unfortunately, that multi-stage behavior and filling in values like that is not possible Service Connections provided by an Extension as ours is; ARM's service connection is built into ADO, where they have much more flexibility to provide those details.

**Comment by jcksonhe** [comment]
Thanks @tehcrashxor , will try this out and report back

**Comment by jcksonhe** [comment]
> Making that API call for our test org returns a different GUID than that test org's Org ID.
> 
> Since the value is being redacted in the logs, you should also be able to find that value from making a Service Connection for Azure Resource Manager. Example:
> 
> Create a new service connection, selecting `Azure Resource Manager` ![image](https://private-user-images.githubusercontent.com/3751389/339581973-58b89f4e-5449-4726-bd32-871a9e55a9f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjI2NzIsIm5iZiI6MTcxODMyMjM3MiwicGF0aCI6Ii8zNzUxMzg5LzMzOTU4MTk3My01OGI4OWY0ZS01NDQ5LTQ3MjYtYmQzMi04NzFhOWU1NWE5ZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMjM0NjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ2ZmVjMzA2ZWM5ZDQ1MzI5OGQzMmVjNDgxZjgzOWM4YTBiODFhNDYwODUxOTYzODM4YTIwN2FkMTBhZjIzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cu_C4QhgkYyx8HF1JnWhOeSSidLcSQiHkBanlyq7Iyc)
> 
> Choose `Workload Identity Federation (manual)`, and hit "Next" ![image](https://private-user-images.githubusercontent.com/3751389/339582030-d17cd022-1043-47dd-8402-ef43c3c467c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjI2NzIsIm5iZiI6MTcxODMyMjM3MiwicGF0aCI6Ii8zNzUxMzg5LzMzOTU4MjAzMC1kMTdjZDAyMi0xMDQzLTQ3ZGQtODQwMi1lZjQzYzNjNDY3YzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMjM0NjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmU3Y2M3NGE4Njg5NGY2MTU0MDFhY2UzZTMxZGY2MTkwOWY3YWEyNjcwMTY3M2QyMWM0ZTI2OGJhZWU0ZTIxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CQyanguNwDHaeP90uz3O6nDjTH6TMfLH5iIB5yDn-mA)
> 
> Fill out any name and click "Next" ![image](https://private-user-images.githubusercontent.com/3751389/339582082-b4823864-e8eb-450c-ad20-404a6ec494b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjI2NzIsIm5iZiI6MTcxODMyMjM3MiwicGF0aCI6Ii8zNzUxMzg5LzMzOTU4MjA4Mi1iNDgyMzg2NC1lOGViLTQ1MGMtYWQyMC00MDRhNmVjNDk0YjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMjM0NjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzNjNzFjZWI3YWJkZjE5MDdlZjBiMTEwYjcwN2JjM2MzYjAwMzNkNzczZDQ5ZjIyNzE1ZTU5MDk2ZWFhYTFhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GMyzE-0Y0lfI5UqNz5Vm2GIVi2DyIa_LuocM4vvTIQc)
> 
> Copy the Issuer field provided on that next page: ![image](https://private-user-images.githubusercontent.com/3751389/339582159-accc5ea8-3cd0-40ba-966d-8b127244ab33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMjI2NzIsIm5iZiI6MTcxODMyMjM3MiwicGF0aCI6Ii8zNzUxMzg5LzMzOTU4MjE1OS1hY2NjNWVhOC0zY2QwLTQwYmEtOTY2ZC04YjEyNzI0NGFiMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMjM0NjEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWRmYjZlOTg2MzljM2FjYjc3MGQ4ZjBiNDY3MjQ5N2JiN2U1ODdjZjk4ZTgyMmI2MzBkMDQ2ZjU3MDZjYmI3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1ZRNf9TB4heptJ8KjJg0HcgyExYXUAgB2zvGY-BWwi4)
> 
> Then feel free to delete the draft ARM service connection.
> 
> We would like to make our own Service Connection behave like the Azure Resource Manager one does, providing those details at creation time. Unfortunately, that multi-stage behavior and filling in values like that is not possible Service Connections provided by an Extension as ours is; ARM's service connection is built into ADO, where they have much more flexibility to provide those details.

This worked!! Thank you so much @tehcrashxor!!
