### ISSUE TITLE
Unpacking Canvas App Issue - PA3999: Unable to parse template file PowerApps_CoreControls_DropdownCanvasTemplate_dataField

### ISSUE THREAD

**Issue by ccolomier** [microsoft/powerplatform-build-tools#931]
When unpacking a .msapp file I am getting this parsing issue. Not sure where it is coming from. I am using modern controls and library components heavily in the app. All up-to-the-minute releases that were made on canvas applications. Wondering if this issue is because of these very new controls.

If not, where might is this issue coming from?

**Comment by cadams619** [comment]
I have a very similar issue just a different description after my code. Never had a problem before until this week. I been using modern controls and component library for a while in the app so I don't think that is your issue.
 PA3999: Unable to parse template file PowerAppsOneGridTemplate_dataField

**Comment by ccolomier** [comment]
Good to know. Will be on the lookout to see if Microsoft has an update they need to make.

**Comment by rfarris2000** [comment]
This is a known issue and MSFT is working on a fix.  First reported here:

https://github.com/microsoft/PowerApps-Tooling/issues/668

**Comment by petrochuk** [comment]
The issue is resolved. If you see it again feel free to reopen.
