### ISSUE TITLE
pac auth create --environment <url> fails "Error: The value passed to '--environment' is invalid. Unable to validate connection to default environment."

### ISSUE THREAD

**Issue by ameed** [microsoft/powerplatform-build-tools#956]
pac version 1.32.8+gf89d946

**To Reproduce**
1. Use pac auth create --environment <<org url>> (e.g, https://orgc54563c.crm4.dynamics.com)
2. Microsoft login control appears
3. Enter credentials (provided env administrator , can also access ppac with this user and do all sorts of operations on env)
4. Authenticate with MFA
5. pac command prompt says " 'user' authenticated successfully "
6. But also says "Error: The value passed to '--environment' is invalid. Unable to validate connection to default environment."

Additional notes:
My tenant is in European region, i tried using pac auth create with both CRM4 and CRM (US region env in my tenant), but always get this error. However, I also have access to a tenant in Canadian region, when i used it with one of theirs environment, it worked.

**Comment by ameed** [comment]
Kindly close this issue. After a lot of cleaning up of some sort credentials being cached somewhere, i made it work. The problem was being caused due to cached credentials due to working with different tenants. I cleaned up windows credentials, then delete saved passwords for different tenants from Edge browser. Then uninstalled Visual Studio Code extension. Then uninstalled Power CLI tools (as installed by MSI) and deleted the folder C:\Users\<you>\AppData\Local\Microsoft\PowerAppsCLI and then reinstalled MSI and also Visual Studio Code extension

**Comment by ameed** [comment]
closing the issue

**Comment by yamgarcia** [comment]
I believe this should stay open until someone figure out how to fix it. 
It doesn't make much sense to see "<User email> authenticated successfully" and then "Error: The value passed to '--environment' is invalid. Unable to validate connection to default environment.".
