### ISSUE TITLE
pac cli cmt (Configuration Migration Tool) Ignoring Duplicate Primary Attributes with Different Parent Record

### ISSUE THREAD

**Issue by mfux2748** [microsoft/powerplatform-build-tools#957]
**Describe the bug**
We have a custom self-referencing table, let's say Market Segment. 
The table has two columns:
- Parent Market Segment (lookup to Market Segment Table)
- Name (primary name column)

Let's say we have two records
Record 1:
Parent Market Segment: Computers
Name: Processor

Record 2
Parent Market Segment: Printers
Name: Processor

**To Reproduce**
Starting condition: record 1 is available with same GUID in DEV and PROD environment

1. Create record 2 in DEV environment
2. Use pac cli cmt tool to deploy the Market Segment table to PROD; schema file contains marketsegmentid (GUID), Name and Parent Market Segment Table
3. Export from DEV
4. Import to PROD
5. Record 2 is missing in PROD, no error message in log

**Expected behavior**
Record 2 should be available in PROD because it has a different GUID in DEV, although it has the same value in the primary attribute
Minimum is to show an error message if values are not transferred (in our case 1/3 of the records were missing)

**Screenshots**
Can't do without disclosing company information; I hope the example is good enough to reproduce

**Desktop (please complete the following information):**
Migrator version: 4.0.0.110 64-bit; see screenshot
<img width="224" alt="image" src="https://github.com/microsoft/powerplatform-build-tools/assets/139461209/df12b2d0-d96c-4875-8e1d-6c87787a61de">

**Additional context**
If I deduplicate the primary name column (i.e. "Processor Printer") record is imported without issues, but this does not make much sense from business perspective.
I would have expected the cmt tool to look only for GUID and treat the primary name column like any other column, means not use it to resolve lookups
There is no duplicate detection rule activated or even configured on the table, "Apply Duplicate Detection Rules" setting on the table is even disabled.

**Comment by tehcrashxor** [comment]
> I would have expected the cmt tool to look only for GUID and treat the primary name column like any other column, means not use it to resolve lookups

Your expectations do not match the documentation:
https://learn.microsoft.com/en-us/power-platform/admin/manage-configuration-data
![image](https://github.com/microsoft/powerplatform-build-tools/assets/3751389/634257af-9421-44ba-b69c-d06e6486e578)

Entity ID GUIDs are expected to be unique, even across copies of the "same" entity in a different environment.  They cannot be reliably used for that comparison, hence the documented behavior.

**Comment by mfux2748** [comment]
@tehcrashxor , thanks for the clarification. Could you confirm the uniqueness condition is to be defined by creating a key for the table?

**Comment by tehcrashxor** [comment]
Creating the uniqueness definition is done in CMT while generating the data schema -- [see step 12 in the documentation here](https://learn.microsoft.com/en-us/power-platform/admin/create-schema-export-configuration-data#create-a-schema-and-export-configuration-data)
