### ISSUE TITLE
Azure DevOps Pipeline PowerPages Fails

### ISSUE THREAD

**Issue by mikevalentinecanteen** [microsoft/powerplatform-build-tools#966]
**Describe the bug**
The issue with Azure DevOps pipelines not being able to deploy portals using the CLI has returned.  I had reported this May 24 and it was resolved however I think the latest update to the PAC CLI that was merged yesterday broke this again.

**To Reproduce**
Run a DevOps pipeline job that deploys portals.  It will fail with the error message: 

2024-07-10T20:21:42.4065602Z Error: Power Pages entities for standard data model (v1) aren't available on this org, please install required packages on this org. If you are trying to upload to enhanced data model (v2), pass model version as "2". For more information see https://learn.microsoft.com/en-us/power-pages/admin/enhanced-data-model#data-model-power-platform-cli-parameters .

**Expected behavior**
The portal to deploy to downstream environments.

Azure DevOps using Windows-Latest image.

**Comment by mikevalentinecanteen** [comment]
How can I roll back the version DevOps uses for deployments. We have a production release Friday night and it’s 100% critical that this is successful.  Should I open a Sev A support ticket?

**Comment by petrochuk** [comment]
Sorry you are having this issue. We are in process of rolling out the fix

**Comment by mikevalentinecanteen** [comment]
Please let me know as soon as this is fixed.

Mike

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Andrew Petrochuk ***@***.***>
Sent: Wednesday, July 10, 2024 6:33:56 PM
To: microsoft/powerplatform-build-tools ***@***.***>
Cc: Valentine, Mike ***@***.***>; Author ***@***.***>
Subject: [External] Re: [microsoft/powerplatform-build-tools] Azure DevOps Pipeline PowerPages Fails (Issue #966)

Sorry you are having this issue. We are in process of rolling out the fix — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <microsoft/powerplatform-build-tools/issues/966/2221639205@ github. com>
ZjQcmQRYFpfptBannerStart
External:
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/K2m87zzkuLY!djNzXxhEa1R_yKsKjhRsT3eN-d5hNsp7xlWcqoRyHqMJ9uoTyaZ7bc61Wo6AG1iWjz-ZXvDITMDH5WE3ltEwB61ojTv2XIbUEHvbn4Uf5uSHY9qLk4NPXKVsVyrrSwevrsWv5r0$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

Sorry you are having this issue. We are in process of rolling out the fix

**Comment by tehcrashxor** [comment]
Should now be resolved with [v2.0.74](https://github.com/microsoft/powerplatform-build-tools/releases/tag/v2.0.74)
Note that ADO may take a few minutes to pick up the change, and the version used in any given pipeline run can be found at the top of the logs for any of the PPBT tasks.
