### ISSUE TITLE
Pac auth create using Client Secret contain '-' at the start in Secret

### ISSUE THREAD

**Issue by hoangducdev** [microsoft/powerplatform-build-tools#992]
How can I enter the client secret contain dash sign? The pac command treat '-' as an argument. It say "An unknown argument -aaakkd******************************" was passed.

pac auth create --name MyOrg-SPN --applicationId 00000000-0000-0000-0000-000000000000 --clientSecret '-aaakkd******************************' --tenant 00000000-0000-0000-0000-000000000000

System:
OS: Windows 10 10.0.19045
CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1355U
Memory: 17.23 GB / 39.68 GB
Browsers:
Edge: Chromium (123.0.2420.97)
Internet Explorer: 11.0.19041.4355

**Comment by petrochuk** [comment]
PAC CLI supports [data URI scheme](https://en.wikipedia.org/wiki/Data_URI_scheme) for any argument to encode special characters in [Base64](https://www.base64decode.org/). In your example you can pass

`auth create --name MyOrg-SPN --applicationId 00000000-0000-0000-0000-000000000000 --clientSecret data:text/plain;base64,LWFhYWtrZCoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKg== --tenant 00000000-0000-0000-0000-000000000000`

`LWFhYWtrZCoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKg==` is base64 encoded `-aaakkd******************************`

**Comment by hoangducdev** [comment]
Thanks Petrochuk, It worked
