### ISSUE TITLE
Going Mad with 'Unexpected Error Occurred' error when trying to use deployment settings file

### ISSUE THREAD

**Issue by bri-bh** [microsoft/powerplatform-build-tools#994]
Hi,

I've been working on creating guidelines for proper ALM in my organization because right now everything is being built in our default environment and I would like to setup automated deployments from DEV to QA to PROD. To test this deployment pipeline, I am trying to automate the deployment of a solution built in the default environment to our DEV environment using a deployment settings file, but I cannot get it to work, I receive the same error every time. The release pipeline works when I uncheck using the deployment settings file, so I know that there's some issue with it, what the issue is, I'm not sure. I have shared the connections I made in my target environment (In this case the DEV environment) and given the service principal App can use+share permissions on all connections. Below is my deplyments settings file code and the connection reference IDs used are the ones I created in my DEV environment. I have tried remaking the connections and deleting any connection references that were made when I deployed it successfully without the deployment settings file by creating a temp solution and deleting them from the environment. I' not sure where to go especially given the error is so vague. 

Can anyone assist with this? 

[tasklog_8 (1).log](https://github.com/user-attachments/files/16591573/tasklog_8.1.log)

`{
  "EnvironmentVariables": [
    {
      "SchemaName": "new_shared_sharepointonline_15307d8d716c4223a579fe7fe858f62f",
      "Value": "IT Capital Time Tracking - https://bhaz.sharepoint.com/sites/ITCapitalTimeTracking2",
      "Name": {
        "Default": "IT Capital Time Tracking - https://bhaz.sharepoint.com/sites/ITCapitalTimeTracking2",
        "ByLcid": {
          "1033": "IT Capital Time Tracking - https://bhaz.sharepoint.com/sites/ITCapitalTimeTracking2"
        }
      }
    },
    {
      "SchemaName": "new_shared_sharepointonline_40baa84dfb1c4bc2a658873f0080566b",
      "Value": "Workday_Projects",
      "Name": {
        "Default": "Workday_Projects",
        "ByLcid": {
          "1033": "Workday_Projects"
        }
      }
    },
    {
      "SchemaName": "new_shared_sharepointonline_4548219ae86143669217a573bb04644c",
      "Value": "ADO_Team_Managers",
      "Name": {
        "Default": "ADO_Team_Managers",
        "ByLcid": {
          "1033": "ADO_Team_Managers"
        }
      }
    },
    {
      "SchemaName": "new_shared_sharepointonline_671b10ed1a1841d2af3d1aed00aa513c",
      "Value": "Report_Cycle_Dates",
      "Name": {
        "Default": "Report_Cycle_Dates",
        "ByLcid": {
          "1033": "Report_Cycle_Dates"
        }
      }
    },
    {
      "SchemaName": "new_shared_sharepointonline_ae934090e40c4a998e00a6cde9a2d304",
      "Value": "Employees",
      "Name": {
        "Default": "Employees",
        "ByLcid": {
          "1033": "Employees"
        }
      }
    },
    {
      "SchemaName": "new_shared_sharepointonline_c20a334d2716493c96f3762da105212c",
      "Value": "Workday_Assets",
      "Name": {
        "Default": "Workday_Assets",
        "ByLcid": {
          "1033": "Workday_Assets"
        }
      }
    },
    {
      "SchemaName": "new_shared_sharepointonline_ec35accec6414523aa2219b488d0ea03",
      "Value": "Capital_Expense_Report",
      "Name": {
        "Default": "Capital_Expense_Report",
        "ByLcid": {
          "1033": "Capital_Expense_Report"
        }
      }
    },
    {
      "SchemaName": "spadmins_shared_sharepointonline_45c65520881e476ca83336f92ad9f8fd",
      "Value": "CapEx_Approver_Reports",
      "Name": {
        "Default": "CapEx_Approver_Reports",
        "ByLcid": {
          "1033": "CapEx_Approver_Reports"
        }
      }
    },
    {
      "SchemaName": "spadmins_shared_sharepointonline_cbce7a1cfea14468a86a6cca8d0e7b26",
      "Value": "CapEX_WorkItems_Reports",
      "Name": {
        "Default": "CapEX_WorkItems_Reports",
        "ByLcid": {
          "1033": "CapEX_WorkItems_Reports"
        }
      }
    },
    {
      "SchemaName": "spadmins_shared_sharepointonline_f32657c7b8234c58913e6b90dae28729",
      "Value": "ADO_JIRA_WorkItems",
      "Name": {
        "Default": "ADO_JIRA_WorkItems",
        "ByLcid": {
          "1033": "ADO_JIRA_WorkItems"
        }
      }
    }
  ],
  "ConnectionReferences": [
    {
      "LogicalName": "spadmins_sharedexcelonlinebusiness_1a421",
      "ConnectionId": "shared-excelonlinebu-24362b67-bfb6-4f1c-9679-78c85ec9cfb2",
      "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_excelonlinebusiness"
    },
    {
      "LogicalName": "spadmins_sharedmicrosoftforms_753d0",
      "ConnectionId": "shared-microsoftform-ae8dd9d6-1920-473e-a5ec-5295bfbf6629",
      "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_microsoftforms"
    },
    {
      "LogicalName": "spadmins_sharedoffice365_a6d37",
      "ConnectionId": "shared-office365-6a21111c-893d-46d4-9eb0-462a763d703d",
      "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_office365"
    },
    {
      "LogicalName": "spadmins_sharedpowerbi_f3c71",
      "ConnectionId": "shared-powerbi-5d29cfc6-1dce-43f7-a439-6794b0cf4b02",
      "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_powerbi"
    },
    {
      "LogicalName": "spadmins_sharedsharepointonline_15b40",
      "ConnectionId": "shared-sharepointonl-bd4be84a-96b1-45e9-a721-3ebf22bf84c4",
      "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_sharepointonline"
    },
    {
      "LogicalName": "spadmins_sharedsql_f13bf",
      "ConnectionId": "0cb2ec2edfe0421a9f42291b30c675ce",
      "ConnectorId": "/providers/Microsoft.PowerApps/apis/shared_sql"
    }
  ]
}`

**Comment by mikefactorial** [comment]
@bri-bh you can usually get more useful error messages than what shows up in the logs by looking at the solution history in the maker portal to narrow down the issue

**Comment by bri-bh** [comment]
> @bri-bh you can usually get more useful error messages than what shows up in the logs by looking at the solution history in the maker portal to narrow down the issue

There is no solution history. I'm trying to deploy it as a new solution to a new environment via Azure Dev Ops. The error message is from the deployment agent job log in ADO.

**Comment by mikefactorial** [comment]
@bri-bh if you go to Solutions in maker portal and select See History you will see the failed solution import in the target environment for any solution import that started and failed or succeeded.

**Comment by bri-bh** [comment]
> @bri-bh if you go to Solutions in maker portal and select See History you will see the failed solution import in the target environment for any solution import that started and failed or succeeded.

Omg you genius, I finally got it working because of this tip. I didn't realize there was solution import history on solutions that didn't yet exist in that environment, thank you so much this helped enormously!
